### ISSUE TITLE
Editable container labels/titles [FEATURE]

### ISSUE THREAD

**Issue by W2PA** [ramdor/Thetis#104]
At present (unless I've missed something) the meter containers have fixed labels or titles, such as "Container 5 TRX1".  When you have more than a small number of containers it becomes difficult to find the one you're looking for.  You have to select one after the other until you find the one containing the meters you want to customize.  Yes, you have the highlight checkbox, but that doesn't make searching for the one you want any easier.

So it would be nice to be able to edit those container labels.  Or, since it's necessary to know whether each is accessing RX1 or RX2, perhaps just add a tag to it to be more descriptive of what's inside.  An example might be "TRX1-5: receive meters", meaning it's container 5 for TRX1 and it contains receive meters.  (Save space by removing the word "Container" from the labels, too.)

For now, I've written a separate note to myself about which containers have which meters.  It'd be nice to not have to do that.

**Comment by oe3ide** [comment]
For a quick check whats inside a container, I hover the mouse-pointer on the container-selection box and scroll the mouse-wheel. With this method I can find each container very easy.

**Comment by W2PA** [comment]
Excellent.  That's much easier, Ernst.  Still, it would be nice to have descriptive names at some point. Not high priority.

**Comment by ramdor** [comment]
yes, turn highlight on and just mouse wheel scroll, that'll be way faster than reading (probably)

**Comment by ramdor** [comment]
option to store notes against a container

![image](https://github.com/ramdor/Thetis/assets/3124967/bdba9ed6-eed3-4283-a047-e91771fc7d40)
