### ISSUE TITLE
[BUG] SSB TX settings change after changing band/mode

### ISSUE THREAD

**Issue by SM3PZG** [ramdor/Thetis#105]
Andromeda CIV Thetis v.2.9.0-8 x64 FW v.2.1.26 

SSB TX settings change after changing band and mode. Example: 20m SSB settings  MIC, COMP CFC, Post CFC, TX EQ, RX EQ Leveler ENABLE. Change band to 40m CW and then 80m CW. Return to 20m SSB and COMP, CFC, TX EQ, RX EQ and Leveler are DISABLE. Post CFC still ENABLE. 

Happens what appears randomly but always when changing BAND and MODE.

Had the same issue with previous Thetis versions.

**Comment by ramdor** [comment]
all those settings are per tx-profile. Are you saving the tx-profile associated with LSB/USB? If any of your bands select AM/DIGL for example a different tx-profile associated with those modes will be loaded. I can not replicate your issue here. Will leave open to see if any other reports.

**Comment by SM3PZG** [comment]
Here is a video showing the problem. Same problem if I check Highlight TX. Its only when switching to digital and back to SSB.
https://drive.google.com/file/d/1fE2jupdDqOfDEK3EN-lpW15of2rVxJfF/view?usp=sharing

**Comment by oe3ide** [comment]
Try to disable "Auto Save TX Profile on change"

**Comment by ramdor** [comment]
many settings are stored per TX profile. Modes fm/am/digi have can have specific tx profiles which of course change many tx settings. Closing as no other reports.
