### ISSUE TITLE
MON does not produce audio with split enabled (VAC) [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#129]
**Describe the bug**

- MON does not produce audio with split enabled.
- Only tested with VAC, have not tested with CODEC audio.

**To Reproduce**

- Configure to use VAC for receive audio.
- Enable MON. Split OFF. Make a transmission. Hear transmitted audio via MON/VAC.
- Enable split. Make a transmission. No transmitted audio heard via MON/VAC.

**Expected behaviour**

- Transmitted audio should always be heard when MON is enabled regardless of radio configuration.

**Desktop (please complete the following information):**

 - Latest build from this repo, master branch, as of 1446 29JUN23 UTC.
 - ANAN-8000DLE, FW 2.1.18, Windows 10 Pro

**Comment by ramdor** [comment]
yep been there for a whole. I found early last year. I have looked into it quickly, but it was not obvious. Issue #4

**Comment by ramdor** [comment]
fixed after some pointers from Warren. Also required changes to the mon volume code. Merged into the master.
