### ISSUE TITLE
[FIRMWARE BUG?]PS would not activate

### ISSUE THREAD

**Issue by ramdor** [ramdor/Thetis#133]
Pure signal fails to lock, there are no feedback values being returned.

Whatever I tried, it was very hit and miss if PS would do anything. Two tone and ssb voice same issue. Intermittant PS with long periods of it doing nothing.

Powered down the radio (button on front) whilst Thetis was running, and let sit for 5 seconds. Thetis WDT obviously timed out and Thetis ran through its power down cycle.

Re-powered on the radio, then clicked power buton on Thits, went into ssb mox, turned ps-on mid tx and all working again fine, including two tone tests. Instant consistant PS lock.

Conclusion, some issue in the 7000dleMK2 2.1.18 firmware after long uptime, say 16 ish hours?

**Comment by w-u-2-o** [comment]
Never seen this. I leave my 8000 on for weeks at a time. Same board as you, same 2.1.18 firmware.

**Comment by ramdor** [comment]
Same here really, but I couldnt get anything to work with PS, restarting software, reboot pc etc etc, everything. Last resort was to power cycle the radio. As soon as I did that it was fine. The radio has been on prob 16hrs today, and it is very warm in here atm, close to 30c ambient. Odd indeed, but why a power cycle on the raido, whislt leaving Thetis running would fix things is anyones guess.

**Comment by laurencebarker** [comment]
Worth checking the  pspeak value in the puresignal dialog. Should be 0.2899 I think. The reason for doing thr G2 change was to set a value of 0.6 or so for Saturn. Just  necking my code hasn't caused the problem.Sent from my Galaxy
-------- Original message --------From: Richie ***@***.***> Date: 19/06/2023  22:11  (GMT+00:00) To: ramdor/Thetis ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [ramdor/Thetis] [FIRMWARE BUG?]PS would not activate (Issue #133) 
Same here really, but I couldnt get anything to work with PS, restarting software, reboot pc etc etc, everything. Last resort was to power cycle the radio. As soon as I did that it was fine. The radio has been on prob 16hrs today, and it is very warm in here atm, close to 30c ambient. Odd indeed, but why a power cycle on the raido, whislt leaving Thetis running would fix things is anyones guess.

**Comment by ramdor** [comment]
Yeah that was one thing I checked Laurence, and it looked fine.

**Comment by w-u-2-o** [comment]
Sometimes firmware needs a reboot!

**Comment by ramdor** [comment]
actually I will change your change in PSForm, function SetDefaultPeaks()  but this was probably not the issue

**Comment by ramdor** [comment]
happened again, only way to recover was to power cycle radio. Closing this as probably just my radio and/or me bombing out the running version of Thetis when in VS debug.
