### ISSUE TITLE
DUP displayed power levels during TX incorrectly scaled [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#137]
**Describe the bug**

- Power levels shown on the panadapter/waterfall are not correctly scaled in DUP display mode during TX. Levels are showing a -24dB error.

- The openHPSDR paradigm has always been to accurately display signal levels referenced to the rear panel input.

- Note: scaling for S-ATT is working correctly. I.e., for a given input level the displayed level does not change with S-ATT.

**To Reproduce**

ANAN-8000: place a calibrated signal generator output on the 8000 external PureSignal feedback input, enable PS, set S-ATT to 0dB and key the radio with 0 drive.

ANAN-7000 (any variant incl. Andromeda): place a calibrated signal generator output on the 7000 bypass input, select "Use Bypass on TX", enable PS, set S-ATT to 0dB and key the radio with 0 drive.

My results are as follows and are accurate to about ±1 dB:

Input level -3 dBm = ADC overload indication.

Input level -4 dBm = panadapter level of -28 dBm

Input level -14 dBm = panadapter level of -38 dBm

**Expected behaviour**

- Levels should be accurately reported and referenced to the rear panel connector (Note: there is no calibration routine to account for the internal path loss, but this should be <1dB so it is probably unnecessary.)

**Desktop (please complete the following information):**

- ANAN-8000DLE, FW 2.1.18, Thetis 2.9.1, Windows 10 Pro.

**Additional context**

- In all cases the RF board routes signals via relays from the rear panel, external connector directly to the SDR RX1 input. The same is true on any 100D or 200D that uses a Rev. 24 RF board, and from the EXT connector on any older units that use previous revision RF boards. I.e. this is a measurement that is effectively referenced to the SDR board RX1 input, not including probably less than 1 dB switching/routing losses.

**Comment by ramdor** [comment]
None of the rx display calibration offset values are used when in TX DUP mode. There are rx display calibration values per radio model defaulted in the software, and adjusted as part of the calibration routine (default 5.259dB for 7000/8000). In DUP mode the display is only shifted with preamp_offset (satt) and the TX offset adjust, as mentioned in #47. I agree a 24dB shift is potentially somewhat alarming however. This happens in function RX1Offset in display.cs.

Question 1: is this issue apparent when a tx output power is measured externally, and the DUP display compared using the internal coupler in a 7000 for example.

Question 2: has this issue been identified with other hardware?

**Comment by ramdor** [comment]
It is differences in the rx view when in cw mode it seems. When I test with TUN @ 10w I get the expected value around -10dBm in DUP view using internal coupler (assuming 50dB atten). However, when I key 10w in cw mode (dup off or on) I only see around, -34dBm or so.

**Comment by w-u-2-o** [comment]
Answer to question 1: Yes. Those are the conditions described in the first post above (but only for an 8000).

Answer to question 2: Not yet. I'll ask for data on the forum.

This is not limited to CW mode. I did the measurements above in USB mode. My bad, I should have noted that up front.

**Comment by w-u-2-o** [comment]
We've got a measurement on a 7000 that matches my results almost exactly: https://community.apache-labs.com/viewtopic.php?f=9&t=4701

**Comment by ramdor** [comment]
@Scott, I don't know how to progress this, without purchasing a sig gen so I can take some readings on my 7000.  Even then my 7000 might behave similar to others in that thread where the correct readings are observed by some.

**Comment by w-u-2-o** [comment]
Hi Richie,

Recommend this be fixed by addressing the problem you noted in your 8 July response to this issue whereby you wrote _"None of the rx display calibration offset values are used when in TX DUP mode."_ Since RX1 is used for both normal receive and DUP receive the same calibration should apply, although there is a slight path loss difference (should be less than 1dB) because the DUP path does not go through the preselection filters (bandpass filters). This tiny difference could be accommodated by means of the existing TX Display Cal Offset adjustment in Setup > General > Calibration. Those who want to be perfect will already have a signal generator to do the normal level calibration and they can use the same to tweak the TX Display Cal value.

Thanks!

Scott

**Comment by ramdor** [comment]
Ok Scott, I have added this :

![image](https://github.com/ramdor/Thetis/assets/3124967/5c06dbff-9d81-48f7-98da-7b59844d68e6)

Do we want an option in Setup to include this in the offset calcs? To me I feel it should be in there all the time as it is probably an error that has been there for quite a long time.

R.

**Comment by ramdor** [comment]
To your other comment ref the path loss in DUP. Do we want to add a config for this so that when in DUP this can be included as well?  Or to change the whole approach and add a specific DUP TX display cal offset iin setup which gets used in DUP mode instead of the other ?

**Comment by w-u-2-o** [comment]
Hi Richie,

Making this an option does not seem to be necessary. As you say, this is a long time error that should be fixed.

TX display cal adjustment should remain as a way to fine adjust any differences in cal between normal RX and DUP RX.

Cheers!

Scott

**Comment by ramdor** [comment]
rx1 display offset calibration now combined with tx display cal offset when in TX DUP on
