### ISSUE TITLE
S-ATT lost after TX [BUG]

### ISSUE THREAD

**Issue by Roturbo** [ramdor/Thetis#140]
Radio ANAN 100D

**Describe the bug**
On RX if i chose for example 31 or less S-ATT i get attenuation and all works fine.

If i go over 31 (32 or more till 61)  after press PTT (TX) the s-att  is off,
just moving 1 up or 1 down with mouse wheel i hear one relay activating 
and the level of attenuation is back again to the value that was set before. 

Other radios like 8000DLE only go to 31 on S-ATT and works also normal, 
i think the bug only affect radios with more attenuation over the regular 31.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'S-ATT'
2. Click on 'chose above 31'
3. Press PTT
4. See error,, the attenuation level goes to zero.

**Expected behaviour**
The expected behaviour above 31 should be the same as bellow 31,, after TX 
the level of attenuation must be the same as before TX. 

**Screenshots**
If necessary i can post a video.

**Desktop (please complete the following information):**
 - OS:  Windows/10/ 64bit  
 - Thetis V2.10.0  
 - Anan 100D Firmware 12.1.8
 - Angelia
 - Protocol 2 (V3.9)

**Additional context**
I have test it,, and at least the 2 last releases have this bug.

Regards 

And tanks for this software.....

**Comment by ramdor** [comment]
This is now resolved and will be in 2.10.2 final release. Many thanks for the report.
