### ISSUE TITLE
Band Stack not saved on exit [BUG]

### ISSUE THREAD

**Issue by W0lpertinger** [ramdor/Thetis#144]
Thetis V10.0.0 x64
Frequencies on the selcted bands are only avaible till the software is closed.
After restarting the software the before choosen frequencies on the selected bands are gone and
some other frequecies are selected form Band Stack 2.

While checking Band Stack 2 the frequency change is shown in that window after switching to
an other band. Coming back to the previos band the before choosen frequence is shown in the list and
VFO A. So far this behavior is ok.

After restarting the software this previus shown frequencies are not anymore in the Band Stack 2 lists.

**To Reproduce**
Steps to reproduce the behaviour:
1. Goto Band 10m
2. VFO A is 28.499.123
3. change frequency to 28.599.123
4. VFO A is 28.599.123
5. Switch Band to 15m
6. VFO A is 21.238.300
7. change frequency to 21.338.300
8. Switch back to 10m
9. Band Stack 2 shows 28.599.123 in list
10. Switch back to 15m
11. Band Stack 2 shows 21.338.300 in list
12. Power off
13. Restart the software
14. Band 15m shows 21.238.300 in Band Stack list
15. Band 10m shows 28.499.123  in Band Stack list

**Expected behaviour**
Thetis V2.9.0 works without this issue.
Checkung the database.xml I figure out the the changed frequencies are never be written to the bandstack section with v2.10.0.
Checking same with V2.9.0 the frequencies can be found in the bandstack section.

**System
Windows 10 x64 with all patches and updates provided by Microsoft update service.

**Additional context**
There is no problem in userrights to save / update the database.xml.

**Comment by W0lpertinger** [comment]
Error log:

Entry : 5:42:34 PM Wednesday, August 2, 2023
Object reference not set to an instance of an object.
---------stacktrace------------
at Thetis.ucInfoBar.UpdateButtonState(ActionTypes action, Boolean bEnabled, Boolean bIncludePopup)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
at Thetis.Setup.AfterConstructor()
at Thetis.Console.get_SetupForm()
at Thetis.Console.ExitConsole()
at Thetis.Console.Dispose(Boolean disposing)
at System.Windows.Forms.Form.WmClose(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
-------------------------------

Entry : 5:42:34 PM Wednesday, August 2, 2023
Object reference not set to an instance of an object.
---------stacktrace------------
at Thetis.Setup.udpateTXProfileInDB(DataRow dr)
at Thetis.Console.ExitConsole()
at Thetis.Console.Dispose(Boolean disposing)
at System.ComponentModel.Component.Finalize()
-------------------------------

**Comment by ramdor** [comment]
Can you make a video of this happening? I can't replicate it here at all, even using the TX profile save button/auto save on change/autosave on exit. I did find an issue with db merge version checking code, which has now been fixed but I dont think it would have caused the issue of not saving last visited frequency to a band stack filter.

In the bandstack, if any entry is highlighted, then it will be updated when you exit thetis, even if return to last used frequency is chosen. If highlighted/selected the only way to prevent it from being updated is to lock it.

**Comment by W0lpertinger** [comment]
I’ll make a video this weekend.

 

 

Vy 73 de DG8DP

Chris

 

 <http://www.dg8dp.de/> www.dg8dp.de

 <http://www.photovoltaik-drohnenservice.de/> www.photovoltaik-drohnenservice.de

 

 

 

Von: Richie ***@***.***> 
Gesendet: Mittwoch, 27. September 2023 02:53
An: ramdor/Thetis ***@***.***>
Cc: W0lpertinger ***@***.***>; Author ***@***.***>
Betreff: Re: [ramdor/Thetis] Band Stack not saved on exit [BUG] (Issue #144)

 

Can you make a video of this happening? I can't replicate it here at all, even using the TX profile save button/auto save on change/autosave on exit. I did find an issue with db merge version checking code, which has now been fixed but I dont think it would have caused the issue of not saving last visited frequency to a band stack filter.

In the bandstack, if any entry is highlighted, then it will be updated when you exit thetis, even if return to last used frequency is chosen. If highlighted/selected the only way to prevent it from being updated is to lock it.

**Comment by ramdor** [comment]
I have had multiple people send me their database, and they worked fine here, so it might be a permissions issue, or related to something like speed of computer during the shutdown process. I have changed some code related to the close down of thetis that might improve things, and fix some nasty issues with the db import (new code will tidy up any issues). Keep any eye out for a test build pre-release at some ponit. Cheers. R.

**Comment by ramdor** [comment]
seems to be resolved now with latest pre-release. Reports that it is now working as expected.
