### ISSUE TITLE
No Data in Mode Form [BUG]

### ISSUE THREAD

**Issue by va7qi** [ramdor/Thetis#145]
When pressing the Mode Form in Andromeda, the form shows up, but it is just a blank window

It worked fine with Steve's versions of Thetis.

**Desktop (please complete the following information):**
 - OS: Windows 10 with the latest updates.

73 de va7qi,           ....Erik.

**Comment by DH1KLM** [comment]
This only worked up to version 2.9.0.6. However, there was an issue with the collapsed/expanded view.
https://github.com/ramdor/Thetis/issues/90 opened Feb. 08, resulted in this commit 
https://github.com/ramdor/Thetis/commit/b4f743f5e303533f500a072dc35e4f19ac5326b7
and Richie set all mode dependent modes to hide and the panel remains blank.
You can make them work again by commenting out the changes. But if the panel is used in expanded view
and switching back to collaped view, you will notice something like this.

![mode](https://github.com/ramdor/Thetis/assets/27503182/78e6b975-c998-4921-afae-29bfbfcd54a6)

![issue](https://github.com/ramdor/Thetis/assets/27503182/2215b379-1488-44a9-af5b-79ed794a7173)

But this only happens in a maximized Thetis window. Draging this windows or minimze it and the panel
returns to the original position.

**Comment by va7qi** [comment]
Hi Sigi,

Yes, I can get the mode form to show in expanded view, but when I switch back to collapsed view, it goes blank again.

BTW, I use a small external monitor, which makes it easier to see the optional displays, such as the PS form and Ampview.

73 de va7qi,                ....Erik.

Sent with Mailbird [http://www.getmailbird.com/?utm_source=signature&utm_medium=email&utm_campaign=SentWithMailbird_Normal&utm_content=Variant2]
On 2023-08-05 07:09:29, Sigi ***@***.***> wrote:
This only worked up to version 2.9.0.6. However, there was an issue with the collapsed/expanded view.
#90 [https://github.com/ramdor/Thetis/issues/90] opened Feb. 08, resulted in this commit
b4f743f [https://github.com/ramdor/Thetis/commit/b4f743f5e303533f500a072dc35e4f19ac5326b7]
and Richie set all mode dependent modes to hide and the panel remains blank.
You can make them work again by commenting out the changes. But if the panel is used in expanded view
and switching back to collaped view, you will notice something like this.
[mode] [https://user-images.githubusercontent.com/27503182/258589301-78e6b975-c998-4921-afae-29bfbfcd54a6.PNG]
[issue] [https://user-images.githubusercontent.com/27503182/258589278-2215b379-1488-44a9-af5b-79ed794a7173.PNG]
But this only happens in a maximized Thetis window. Draging this windows or minimze it and the panel
returns to the original position.

**Comment by ramdor** [comment]
fixed in recent push
