### ISSUE TITLE
transform of code to multi platform capability[FEATURE]

### ISSUE THREAD

**Issue by wwortel** [ramdor/Thetis#146]
Thetis is hooked on Microsoft Windows OS. Many prefer Mac or Linux.
Can Thetis be changed into an open-source code base that can produce native code for a variety of OSs?

**Comment by w-u-2-o** [comment]
Thetis consist of 3 main pieces. WDSP is already ported to Linux and used in piHPSDR and linHPSDR. It would probably not be too much of a stretch to port ChannelMaster. But the console code is pretty much rooted in Windows. Combine that with the tangle of code the console portion is today and it would almost certainly be easier for a developer to start over.

Given that situation, it is unlikely anyone will ever try to port Thetis to Linux.
