### ISSUE TITLE
 BUG   CTUN not saved 

### ISSUE THREAD

**Issue by fifthwheel** [ramdor/Thetis#148]
When CTUN is selected and Thetis is shutdown, it does not come back when Thetis is restarted.  It is not being saved.  I tried a clean install and still the same thing. 
Reverted to 2.9.08 and it is now being saved properly. 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by ramdor** [comment]
CTUN is stored against an entry in the band stack. If that entry is locked it wont be stored. If you have your band stack configured to return to an entry that does not have CTUN stored against it, then it will not be turned on when you restart. Closing as works as expected here.

**Comment by fifthwheel** [comment]
Thank you Ritchie for the explanation.  I have found it works as you described.  I appreciate all your hard work on Thetis. James WD5GWY Sent from my Galaxy
-------- Original message --------From: Richie ***@***.***> Date: 9/23/23  9:18 AM  (GMT-06:00) To: ramdor/Thetis ***@***.***> Cc: fifthwheel ***@***.***>, Author ***@***.***> Subject: Re: [ramdor/Thetis]  BUG   CTUN not saved  (Issue #148) 
CTUN is stored against an entry in the band stack. If that entry is locked it wont be stored. If you have your band stack configured to return to an entry that does not have CTUN stored against it, then it will not be turned on when you restart. Closing as works as expected here.
