### ISSUE TITLE
Thetis not running on korean or japanese Windows

### ISSUE THREAD

**Issue by DH1KLM** [ramdor/Thetis#149]
Thetis versions greater 2.9.0.3 obviously do not run on Korean or Japanese Windows 10 / 11 versions. 

https://www.facebook.com/groups/5483272138380247/permalink/23915295334751314/
https://yukio-sekiguchi.way-nifty.com/radio/2023/08/post-8f4a18.html

![korean-win10](https://github.com/ramdor/Thetis/assets/27503182/abd99a8f-265a-4c87-99cc-b21244cd9cd0)

To verfiy this behavior I installed a Korean Windows 10 in a virtual machine. I can now confirm that versions greater than 2.9.0.3 do not work. Thetis can be installed, but the error message mentioned appears when the program starts. This also applies to Thetis HL2 Beta 5 from MI0BOT. On the other hand, the version of G7KLJ https://github.com/w-u-2-o/Thetis-2.9.0/releases/tag/2.9.0.31a seems to work on Korean Win10.
[ErrorLog.txt](https://github.com/ramdor/Thetis/files/12479741/ErrorLog.txt)

**Comment by DH1KLM** [comment]
I commented out lines 1160 - 1175 and 1196 - 1198 in ucInfoBar.cs. This led to Thetis also running on the Korean Win10 version.

I don't know how this change will affect Thetis on the fly.

![change](https://github.com/ramdor/Thetis/assets/27503182/07d8f5f5-1654-442c-9e76-5a7c94c285fc)

**Comment by ramdor** [comment]
hey Sigi, if you have a VM running to test on, can you just comment out the two likes that assign the Font, and leave the rest of it there and run the test. If I change my windows over to the Korean language it runs ok. So comment them like this and run test again...

![image](https://github.com/ramdor/Thetis/assets/3124967/abe2ac15-2dd4-4263-aab9-5a8ef27a99b7)

**Comment by DH1KLM** [comment]
Hi Richie, I'll give it a try and report back.

**Comment by ramdor** [comment]
Hey Sigi,  Thanks for the testing. Can you try building and testing the following branch. It has a couple of changes to ucInfoBar.cs

https://github.com/ramdor/Thetis/tree/FixForKoreaJapanResizeIssue

Thanks. R.

**Comment by DH1KLM** [comment]
Hello Richie. Looks good so far. At least on korean OS. Perfect job.

![korean](https://github.com/ramdor/Thetis/assets/27503182/4ca04624-de69-4c53-8ba7-50971ec1165f)

**Comment by ramdor** [comment]
now resolved
