### ISSUE TITLE
[BUG] Not remembering Setup/Audio/VAC1 info

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#159]
Some item selections in VAC1 VAC2 are not being remembered  across restarts.
They are in the database.xml file as "True" but the checkboxes are always disabled or combo boxes at default
Enable VAC1
Buffer Size
Auto Enable
Output to VAC

**Comment by ramdor** [comment]
Hey Mike, cheers for the report. Just one thing to mention is that to store the enabled state, and many other settings, of VAC 1 or 2 you need to save the TX profile. Therefore, by definition, different TX profiles can have different VAC enabled states. Are you saving the TX Profile and did you check the txprofile data in the database ? The check state for the various buttons/checkbuttons are modified when the tx profile settings are applied essentially over the top of the state table data.

This video covers it : https://www.youtube.com/watch?v=ReKDw5fWLh8

**Comment by mdblack98** [comment]
OK...that works...guess that was a change I missed.

**Comment by ramdor** [comment]
It has been like that a long long time Mike. Since before I even owned an anan. It can be very confusing when it doesnt do things one expects, and is 99% of the time down to needing to save the tx profile.
