### ISSUE TITLE
[BUG] TCI Server does not give correct IF: commands: Sends CW pitch instead of IF QRG inside panorama upon QRG changes 

### ISSUE THREAD

**Issue by rsaue** [ramdor/Thetis#162]
Hi,
This report is related to closed bug report § #62 regarding wrong QRG synchronisation with SDC (Software Defined Connectors - lw-sdc.com) , 

The fix on #62 did not end the sync problem with SDC as the problem now is that TCI is off sync with approx twice the CW pitch. This can partly be resolved by adjusting the offset within SDC but it does not fix all the problems with SDC, making especially the Skimmer option less useful connected to Thetis. 

According to SDC author Yuri, UT4LW, SDC reads the TCI IF: command and that the sync problem is due to the implementation of the  IF: command in Thetis. 

I am no programmer so finding the problem i compared the TCI server log readout from SunSDR ESDR3 program with the readout from Thetis (master as of today). This reveals that Thetis TCI server always and only sends the CW pitch offset  upon QRG changes in Thetis: (RX1  and RX2 alike)  

In my setup the CW pitch is 600 Hz. When QRG changes in Thetis, it will always send the following TCI command to external devices (this for RX1): 

               if:0,0,-600;

I guess this is according to code in TCIServer.cs line 558 (?)

If intended the implementation is not according to TCI spec 1.9, which in section 5.2 Bidirectional Control Commands states for the IF-command: 

![TCI IF-command_spec](https://github.com/ramdor/Thetis/assets/22942440/b56780ee-b90a-4c28-a42c-ea1e60948613)

I hope this can be looked into when time permits, as the SDC program is a very good DX companion with SunSDR and Flexradio, and could also be he same with systems using Thetis. 

73 de LB2EG Richard

**Comment by ramdor** [comment]
hopefully this has been resolved now. If you use it with CTUN turned off, it will probably be fine, however with CTUN on previously it did not include an IF message along with the DDC change. The fixes have been pushed to the main master branch and will feature in a future release. Thanks for reporting the issue. #164
