### ISSUE TITLE
Reset waterfall when TX/RX  changes

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#166]
The waterfall does not reset when TX/RX toggles.
So it becomes pretty useless for things  like watching for VaraModem responses.
Here's a video where you can see the undesirable behavior.
https://www.dropbox.com/scl/fi/m0zvjlm3ijmvzg0aa0kfg/Recording-2023-09-28-101934.mp4?rlkey=9pg7jtyn250b12yk7u1w7lole&dl=0

**Describe the solution you'd like**
When changing from TX to RX or  RX to TX zero out the waterfall display.

**Comment by ramdor** [comment]
options added in dev branch for this. To clear spectral data, and one to clear down wdsp bins.
