### ISSUE TITLE
Upgrade to use .Net 4.8.1

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#197]
Should upgrade to .Net 4.8.1 in the build.
Bug fixes plus ToolTip improvements and accessibility improvements.

**Comment by ramdor** [comment]
has been updated in the dev fork. Will be included in the 2.10.2.3 release at some point

**Comment by ramdor** [comment]
v2.10.3.1 has reverted back to v4.8.0. Legacy OS' not supported by 4.8.1 and we dont' really get anything of benefit as it stands from it anyway.

https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-481
