### ISSUE TITLE
[FEATURE] WASAPI Support/Upgrade Port Audio

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#200]
I would like to formally request that the PortAudio library be updated to a more modern version, specifically to add support for WASAPI, both shared and exclusive modes.

WASAPI has the potential to bring lower latency VAC options to operators without having to resort to ASIO, and to allow for greater flexibility.

With WASAPI I am able to run a Ringbuffer of 12ms and a PortAudio buffer of 0ms, using a motherboard sound card.
Older MME or DirectSound require at minimum 500% longer ringbuffers and around 55ms minimum PortAudio buffer.

**Comment by ramdor** [comment]
version [2.10.3] will see PortAudio updated to the release 19.0.7 that happened in 2021. I am not using WIP progress PortAudio repo.

![image](https://github.com/ramdor/Thetis/assets/3124967/80d59bf3-d6c4-48f3-894f-0dade35631fc)

![image](https://github.com/ramdor/Thetis/assets/3124967/870012a8-f0f3-4de6-8188-2838673539e3)

**Comment by RdWing** [comment]
Thanks @ramdor, you rock.
