### ISSUE TITLE
leftover in expanded view

### ISSUE THREAD

**Issue by DH1KLM** [ramdor/Thetis#201]
There is another leftover if opening the "mode settings form" in Andromeda Button Bar and then switch back from "Collapsed View" to "Expanded View".
The leftover can also be right clicked to open the setup page.

Compiled from latest sources 10.10.23

![leftover](https://github.com/ramdor/Thetis/assets/27503182/d0a9e1ac-05be-45cd-9b28-b00f7a57c59e)

**Comment by ramdor** [comment]
hey sigi, which top bar are you using in collapsed mode?

![image](https://github.com/ramdor/Thetis/assets/3124967/18f6c57f-760f-4202-b6da-a6c6b5c88c29)

**Comment by ramdor** [comment]
ok found issue, thanks for report
