### ISSUE TITLE
[BUG] Very high CPU utilization

### ISSUE THREAD

**Issue by torrenthd** [ramdor/Thetis#207]
Looks like Thetis 2.10.2 is using more CPU power than the previous releases.

Could you please test and report?

**Comment by ramdor** [comment]
I have tested against 2.10.1.0 and it is the same on my machine. The render of the display is actually a tad faster. I just ran cpu and memory profiler through vs and nothing untoward. I've spent about an hour checking for possible causes but nothing found atm.

![image](https://github.com/ramdor/Thetis/assets/3124967/d8d7120a-9b0b-430b-a409-b47f2b9f3a9e)

**Comment by ramdor** [comment]
I notice in that screenshot Thetis has moved into 'efficiency mode'. It didn't seem to change the cpu usage.

**Comment by torrenthd** [comment]
Richie, thanks for your time and testing.

My Thetis process is not running in efficiency mode.

My CPU utilization on a 8 core/16Threads Ryzen processor jumps from 5 to 10%. If I remember well, previously it was arround 3-6%. 

Later today I will install a previous version and make som comparisons.
Thinking about it I remembered that 2 weeks ago I installed a new BIOS version to mitigate some Ryzen vulnerabilities, this could be te culpcript!

**Comment by torrenthd** [comment]
Richie,

Tested a few previous versions using my current database and all of them are showing similar CPU utilization.

Then installed from scratch 2.10.2 without database and made a partial/quick setup config (audio, video, display setting, multimeters, etc) and seems that my CPU utilization went down a little bit (by 2-3%).

When I have some time I will make screenshots of my recent config and an entire database redo.

I will post my results.

**Comment by ramdor** [comment]
hi, cheers for the testing. Perhaps send my the two database? the one where load is low, and the other where load is higher?  I can run a diff and check just to make sure. My email is over on QRZ, callsign MW0LGE. 

I wonder if you have dedicated gpu card? One thing to check is perhaps embedded graphics is enabled by default in the bios, which might be the issues as Thetis right now doesn't give the option to choose adapter. It just uses DirectX 'hardware' which may be defaulting to embedded gpu on your system. If it is on in the bios, try turning it off, and try Thetis again.

Thanks, Richie.

**Comment by torrenthd** [comment]
Richie, using a dedicated GPU on my two setups, My Ryzen processors don't have embeded graphics.

Give me some time to redo my database. If there is a significant difference in CPU utilization I will send you  both for sure.

Thanks for your time!

**Comment by ramdor** [comment]
still having issues?

**Comment by torrenthd** [comment]
No more testing yesterday, I went back to my old database.

**Comment by torrenthd** [comment]
Richie,

Testing today I noticed that i can not import my saved TX profiles to a new database.

I was testing my stored TX profiles to compare CPU utilization but unfortunately I can't.

I'm going to rebuild the database from scratch

**Comment by ramdor** [comment]
yes there is an issue importing exported TX profiles. Working on it right now

**Comment by ramdor** [comment]
TX profile import issue fixed [v.2.10.2.2](https://github.com/ramdor/Thetis/releases/tag/v2.10.2.2)

**Comment by ramdor** [comment]
Hi, I am closing this as I have found no cause for any additional CPU load to this extent. That coupled with reports over on the forums that CPU load issues are not a thing of concern. If still an issue please produce a video, which shows a clean install (ie no installed thetis versions), then installing an old version that produces cpu load X, followed by an uninstall, then a reinstall of a new version that produces cpu load X+Y. Also include the databases from both.

Cheers, Richie.

**Comment by torrenthd** [comment]
GM Richie,

Just finished my database config from scratch.

I must test it further, but my first impresions are that, CPU utilization starting from a clean database, is on average a little bit lower. Peaks are also on the 9-10%, but now, I can see my CPU going down to 3%.

Today I will make some more comparisons and let you know.

If you can keep this issue open until sunday night will be nice.

Thanks

**Comment by mdblack98** [comment]
Are you looking at your task manager or at the CPU utilization in Thetis?
Did you know you can select System/Thetis only on the Thetis CPU item?

**Comment by torrenthd** [comment]
I know, but CPU utilization in Thetis is not accurate in Windows 11. I have also a taskbar monitor app and it is not accurate as well.

I'm looking at my task manager. Thetis shows 1-2% CPU utilization and task manager is about 5-10%.

**Comment by mdblack98** [comment]
On my system Thetis (Thetis only) is showing 2%, Task Manager shows 3.4%, and System Informer shows 2.5%.  I woulI much prefer systeminformer as it give lots of control of things.https://www.systeminformer.com/

Found  this -- I do have an AMD Ryzen 9 here...I'll have to test  this when I reboot next...participating in the eclipse watch right now so don't want to reboot.

Turn off C-state efficient mode

Disabling the C-state mode can solve the problem of Task Manage showing wrong CPU usage. This can be a good fix for users with AMD processors. To perform this method, use the following steps:
   
   - Turn the power off for your Windows PC
   - To access the UEFI/BIOS settings, power your PC on and keep on pressing DEL, F2, F12, or any other buttons depending on your computer manufacturer.
   - Navigate to System Utilities or, at times, Advanced CPU Settings.
   - Now, select Platform Configuration or something like System Configuration.
   - Look for Power and Performance, or its similar options.
   - You will see C-state efficient mode or something like Global C-state Control. Disable it.
   - Save the changes and restart your computer.


Mike W9MDB
 

    On Saturday, October 14, 2023 at 09:25:32 AM CDT, torrenthd ***@***.***> wrote:  
 
 


I know, but CPU utilization in Thetis is not accurate in Windows 11. I have also a taskbar monitor app and it is not accurate as well.

I'm looking at my task manager. Thetis shows 1-2% CPU utilization and task manager is about 5-10%.

**Comment by torrenthd** [comment]
Mike, thanks for the tip!

I also use Ryzen processors in my two setups. I will check The C-state option in my BIOS.

**Comment by torrenthd** [comment]
Richie,

I've compared CPU utilization between my two databases, the new one I've rebuild from scratch and the old one that was imported in so many Thetis versions.

I can't really find a big difference in CPU utilization. Seems to me that de new one, on average, uses just a little bit less CPU power, but nothing to worry about.

Tomorrow I will be back to my home QTH (right now I'm my second QTH in the mountains using my radio remotely) and I will test there both new & old databases. 

You can close this if you want.

Thanks a lot!

**Comment by torrenthd** [comment]
Mike, tested C-state and it did the trick!. It is not exactly the same reading from task manager, but quite close...

Unfortunately if you disable C-state, unused core don't go to sleep anymore.

Thanks anyway!

**Comment by ramdor** [comment]
any updates? I don't really think there is anything I can find/fix this end

**Comment by torrenthd** [comment]
GM Richie!

Unfortunately I had no time to do more testing in my home qth nor in the next comming days.

You can close this issue.

Thanks for your support!
