### ISSUE TITLE
[BUG] Quick split & VFO Sync error

### ISSUE THREAD

**Issue by torrenthd** [ramdor/Thetis#208]
Quick split function doesn't work as expected when you enable it with "VFO Sync" activated.

If you have "VFO Sync" activated prior to click on "QPLT", it adds the configured offset frequency to both VFOs A & B instead of just adding it to VFO B.

**Comment by ramdor** [comment]
replicated, nice catch thanks. Yep, because the vfosync is on, the change to VFOB is copied over to VFOA before the check to turn off vsync because split is now on.

**Comment by ramdor** [comment]
fixed and v2.10.2.1 released

**Comment by torrenthd** [comment]
Thanks!
