### ISSUE TITLE
[FEATURE] Quick split 

### ISSUE THREAD

**Issue by torrenthd** [ramdor/Thetis#211]
What about adding an option to Quick split function to automatically add or substract the offset frequency depending on USB or LSB.

Usually on USB band split is always positive and on LSB bands uses to be negative.

Also will be nice to have an option to reactivate "VFO Sync" on split exit.
Thanks!

**Comment by ramdor** [comment]
a) I did mention this to folks that do alot of dx'ing and it was decided that 99% of the time it is UPx even for low band DX stations, so didn't bother implementing it this time. May look at it in future perhaps.

b) the reactivate should happen if it was turned on before QSPLT button on main UI is pressed, it should return it to previous state. This state is not tracked through shutdown/restart however.

Richie.

**Comment by torrenthd** [comment]
Didn't noticed FVOsync reactivation yesterday.

Thanks!

**Comment by ramdor** [comment]
yeah, if you are running release [v2.10.2.1](https://github.com/ramdor/Thetis/releases/tag/v2.10.2.1) then it will turn back on if it was previously on

**Comment by torrenthd** [comment]
That's fine for me, you can close if you want.
