### ISSUE TITLE
RIT & XIT in Andromeda[BUG]

### ISSUE THREAD

**Issue by va7qi** [ramdor/Thetis#212]
RIT works fine in Andromeda, but when selecting XIT the offset shows in the RIT box and AFAIK the transmit frequency does not change when the XIT encoder is operated.

The problem has been there for several releases back.

73 de va7qi.            ....Erik.

**Comment by ramdor** [comment]
@laurencebarker Looks like the code in ExecuteEncoderStep will always update RIT if RIT is checked. There needs to be some state used to determine if encoder is adjusting RIT or XIT.

![image](https://github.com/ramdor/Thetis/assets/3124967/15680521-3683-453d-9a8a-acc405164a87)

**Comment by laurencebarker** [comment]
What do you have that encoder set to control? The default is RIT and regardless of whether RIT or XIT is selected, the RIT offset is adjusted.

Change the encoder to be "selectable RIT/XIT" to have the control edit RIT or XIT depending on what is selected. As far as I can see, that's exactly what it does now.

**Comment by va7qi** [comment]
Thanks Laurence, that was the trick.  I guess I relied on the default.  Lesson learned.

73 de va7qi,             ....Erik.
On 2023-10-19 11:42:08, Laurence Barker ***@***.***> wrote:
What do you have that encoder set to control? The default is RIT and regardless of whether RIT or XIT is selected, the RIT offset is adjusted.
Change the encoder to be "selectable RIT/XIT" to have the control edit RIT or XIT depending on what is selected. As far as I can see, that's exactly what it does now.
