### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by torrenthd** [ramdor/Thetis#213]
Missing "2TON", "ZTB", "blobs", "PEAK" and "Tune slider" graphics/buttons when installing Thetis from scratch.

**Comment by ramdor** [comment]
One day we will get around to rebuilding the paquet builder self extracting archive with some of the updated skins. It is why we currently include the links to the skin providers in the release notes.

The default ones you want to add to add are:
https://bit.ly/3PSv4kh

Skins :
W1AEX Rob Skins - http://www.w1aex.com/hpsdr/hpsdr.html
OE3IDE Ernst Skins : https://www.oe3ide.com/wp/thetis-skin/
My IK3VIG updated buttons (not whole pack) : https://bit.ly/3PSv4kh

**Comment by ramdor** [comment]
Paquet builder Freeware edition does not allow one to remove the destination folder prompt anymore. There is an option to prevent user editing, but it still shows. Only the next tier up at a price of EUR99.00 will resolve this.

**Comment by torrenthd** [comment]
Thanks Richie.

**Comment by ramdor** [comment]
this will become easier with new skin server system due to be included in [2.10.2.3] release at some point. It is now in the dev branch.
