### ISSUE TITLE
RX and TX antenna change from Console [FEATURE]

### ISSUE THREAD

**Issue by Roturbo** [ramdor/Thetis#214]
Is your feature request related to a problem? Please describe.
A clear and concise description of what new feature you are thinking of.

**The actual antenna switching for RX and TX is not very usable, it need 2 clicks 
to change antenna and is not very precise.**

**Also, it only allow change of antenna inside ham bands, if using L/MW, SWL
the antenna can´t be selected from console, this is only possible on 
General--Ant / Filters / Antenna .**

Describe the solution you'd like
A clear and concise description of what you want to happen.**

**A small box with 6 antenna buttons, 3 for TX and 3 for RX present on Console that
can be changed at any time on any band with just one click.**

Describe alternatives you've considered

**If this box was created on same system as the Multi Meters than we can add it to any place
on Console and resize it to fit in small places if need.**

**This extra buttons may or may not have permanent influence over the predefined antenna
on General--Ant / Filters / Antenna,**

**For example, the antenna 1 is the main antenna for all bands, but on Console we can 
select Ant2 for testing, if not saved next time we start Thetis or change and return to same Band 
it will go back to Ant1,, if we right click on Ant2 this antenna than is saved for this band.**

Additional context

**_Just as example, instead of RX1 TX1 it can be ANT1 , ANT2, but RX and TX are more intuitive._**

![Antenna-change](https://github.com/ramdor/Thetis/assets/91867260/73038d33-757b-4a22-a092-7e23b359ed6e)

![3x3](https://github.com/ramdor/Thetis/assets/91867260/953c6b0f-c8e4-4291-aa66-46a3979ce793)

Regards

73´s

**Comment by Roturbo** [comment]
Hello Ramdor.

![image](https://github.com/user-attachments/assets/761d6084-42d9-4619-a317-64d824502fb9)

Many tanks,, changing antenna on the fly turn the usage so much easy.

Step by step the software is getting to the next level.

Regards.

**Comment by ramdor** [comment]
good stuff @Roturbo . Closing this now.
