### ISSUE TITLE
when using transverters , original  frequency does not return to freq after band change [BUG]

### ISSUE THREAD

**Issue by rfmonkey** [ramdor/Thetis#218]
w10, Hermes FW 3.1
sw thetis  2.10.2.2.
just upgraded sw was hoping this was corrected,  The Hermes is strictly  used as an 28mhz IF 

when using **transverters**, say im on 144.200 i qsy to 222  band freq of  222.1

when i come back to 2m band the freq now reads 144.250

in another example i was on 222.1  i go to 2m and then return to 222, the freq is now 222.175 when i have returned.

I have added a short video to show what happens.

tks stu ve2xx

https://github.com/ramdor/Thetis/assets/11407577/86dad4d4-e390-4e6a-a078-9a013aff3bd3

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by ramdor** [comment]
when you use a transverter for the first time, there are no entries in the bandstack, so it wont be able to save anything when you leave 2m for example.  If you dont want any stack entries then you can set the option to return to last used frequency. You can also add entries, lock them off so they dont update when you leave them, things like that. Without any config for the band stack related to the band you are moving to, it will attempt to return to band centre.

**Comment by rfmonkey** [comment]
Great , i just went back to the radio today , and the setting did stay  , great time saver for sure
Thank you for your super dedication Richie  to the development of software, it's been a fun journey from when i first started using anan radios  in 2013,  Fun to have new featured  radios once in a  while!
73's stu
    On Monday, October 16, 2023 at 09:15:10 a.m. EDT, Richie ***@***.***> wrote:  
 
 


when you use a transverter for the first time, there are no entries in the bandstack, so it wont be able to save anything when you leave 2m for example. If you dont want any stack entries then you can set the option to return to last used frequency. You can also add entries, lock them off so they dont update when you leave them, things like that. Without any config for the band stack related to the band you are moving to, it will attempt to return to band centre.
