### ISSUE TITLE
migrating DB from 2.10.0 to 2.10.2.2 fails [BUG]

### ISSUE THREAD

**Issue by grabauter** [ramdor/Thetis#220]
After de-installing and installing the new version, I get this error - thetis startup fails:

![image](https://github.com/ramdor/Thetis/assets/45741629/fb460ac9-1c25-46a7-84c9-d805ffe11f42)

Any idea how to fix this?

**Comment by ramdor** [comment]
tbh, I would uninstall thetis again, restart, then install it. That rawinput error should not happen, as that dll is included in the installation package.

**Comment by grabauter** [comment]
Thank you, deinstall-reboot-install worked, DB got migrated. 73 :)
