### ISSUE TITLE
Make SWR power reduction/warning threshold configurable [FEATURE]

### ISSUE THREAD

**Issue by grabauter** [ramdor/Thetis#221]
Power gets reduced if SWR protection is on, and SWR > 2.0 (limit hardcoded in console.cs).

My Antenna sometimes (depending on the weather) goes up to 2.3, so I need to switch of SWR protection completely. It would be better to increase the limit, because my Anan-100D still handles the higher SWR without any problems.

Would it be possible to make this value configurable?

**Comment by ramdor** [comment]
![image](https://github.com/ramdor/Thetis/assets/3124967/6acf2313-c927-4f35-a71b-eabf90bcb3bd)
