### ISSUE TITLE
PureSignal disabled after using CW on 7000 MKII series hardware [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#226]
**Describe the bug**

- PS works fine initially after launching Thetis and using it in SSB mode. If the user then switches to CW and transmits, then switches back to SSB the user is unable to get PureSignal to operate again until Thetis is restarted.

- This cannot be reproduced on an 8000.

- I've got anecdotal reports from several 7000 CW users on this.

**To Reproduce**

- As above, launch Thetis, operate SSB with PS, operate CW, then switch back to SSB and observe lack of proper PS operation.

- There is a work-around, which is to disable PS-A prior to switching to CW, then enable PS-A after switching back to SSB.

**Desktop (please complete the following information):**

- Windows 10 and 11
- Thetis 2.10.2.2

**Additional context**

- I'm posting this secondhand for a ham friend who is not Github literate. Since I have an 8000 I can't reproduce the problem here, and thus I apologize for the lack of detail in this report.

**Comment by ramdor** [comment]
cant replicate it here

https://youtu.be/KSrq_FM_nm4

but I know for a fact that there is either a firmware issue with PS where it will not lock until my 7000dle MK2 is power cycled (Thetis is not restarted) or something up with my radio.  This happens rarely, but does happen from time to time.

**Comment by RAV52** [comment]
I too have the same issue that Scott stated earlier.
After watching the YouTube video of the test I would like to request or suggest instead of pressing the key button in CWX, please use one of the memories that will send at least a cq cq cq or one of the other canned messages that will send at least a half dozen characters. Once you go back to SSB that's where see PS stop working.
Once we reboot the software PS in SSB behaves as expected.
Thanks 
K1SR
Rob

**Comment by ramdor** [comment]
I have replicated this just. So there is something odd going on somewhere. It didn't happen when I was on 80m, but I flipped band to 20m, PS was working, then did some CW, and then PS stopped.

Video here as a record. You can hear the sadness in my voice at the end.  https://youtu.be/p5_a5LkohbY

**Comment by ramdor** [comment]
ok, i can this this occur on demand now. For me it always happens when I change band. So SSB on 40m, cw, back to ssb fine. However if I move to 20m say, and instantly do some CW I see a short pulse of feedback from PS, then it stops correcting. I come of of CW and flip to SSB and Thetis does not get anymore PS updates from the hardware when breakpointed.  At this point I power cycled the radio and it didn't resolve the issue, however restarting Thetis did.  Needs investigation.

**Comment by w-u-2-o** [comment]
Thank you, Rob, for that critical bit of info I was lacking. I knew it would be a challenge to post this in a secondhand fashion.

**Comment by ramdor** [comment]
yes, for some reason, when switching band and instantly outputting some cw on that new band, there is a very short pulse of PS feedback. After that pulse it stops providing any more feedback in ssb on any band.

**Comment by W2PA** [comment]
A bit more info that might help track this down. 
 
Last weekend I worked on air with the ham Scott is referring to.  Even without changing bands (just remaining on 80m, not even changing frequency), going into CW, sending a few dits then coming back to SSB would disable PS completely.

We tried various ways short of restarting Thetis to recover PS operation (e.g. band/mode changes, TX profiles, cycling the PS button, and other settings and combinations of functions).  Nothing we tried worked once PS became disabled except bringing Thetis down completely and restarting it.  Also tried turning off the Thetis power/start button and restarting only the 7000 hardware, then starting Thetis, which didn't work either.  Only restarting Thetis recovered PS operation and that worked every time.  This all seemed to point to Thetis somehow getting into a strange state that was hard to get out of, after a mode change following CW operation.

I'm glad you can replicate it, Richie.  Like Scott, I can not do so on my 8000.

**Comment by nj2us** [comment]
This may or may not be related. In addition to a receive only antenna (Beverage) that I attach to port RX2, I also attach a preamplified and multi coupled Shared Apex Loop on Ant Port 3, and my primary transmit output is on Ant Port 1. (I leave Port 2 disconnected as an isolation boost). I discovered when using CWX in break in or semi breakin mode, my transmit power appears on Ant Port 3, for a split second as the internal relays are switching. Consequently, this power burst on what is designated as a "do not transmit" Antenna port, has destroyed a strisberg active multicoupler. This all came together for me, while testing the Pure Signal bug with the rest of the gang. I ultimately determined that RF was appearing on the undesired Ant Port by watching it with a dedicated watt meter. This only happens in CW mode as the internal TRX clack back and forth with semi break in delays of approx 250 ms. 
I created a video of the phenomena and will post if none of this makes sense.

**Comment by nj2us** [comment]
Is there any chance that there is a relationship between the Pure Signal issue and "Key-Down (ms)" Delay? My CW Key Down delay is set to 50 ms, and I DO NOT have the pure signal anomaly on either of my 7000 DLE (Blue ser # 0019 and Black ser # 00389)

Jeff NJ2US

**Comment by W2PA** [comment]
Jeff - Good thought.  But I run with 7 ms Key-Down delay and have no such problem.

73, Chris, W2PA

**Comment by ramdor** [comment]
Lengthily investigations with Warren, over some 10hrs and lots of emails, has resulted in a fix made by Warren for at least the issue I could produce where we move to a new band, 20m in the above example, and use CWX. This would cause multiple on/off/resets in PS which resulted in a state where PS would fail when switching to SSB.  I will leave this open until [2.10.3] is released.

**Comment by miguelestrada** [comment]
Hi Richie (and Rob, Chris, Jeff, Scott)

I can confirm this addressed the issue that the original operator had reported (via Scott and Chris) which I could also reproduce in my blueface 7000 (used to be Rick's...).  I had tried last night wihout success, but today's with the changes from Warren seem to do the trick.  Just wanted to let you know... some data points :-) 
Thanks for all you do !!! (and the others of course... you know who you are)

**Comment by ramdor** [comment]
@miguelestrada ah that is good news. Yes we were trying various things for hours until I hacked in loads of debug messages to monitor the state engine and other things in PS. Warren spotted an odd sequence of events, and made some changes.

**Comment by W2PA** [comment]
Great news, Richie - congrats to you and Warren for tracking this down - it sounds like it was quite a difficult one to nail.  I'm now wondering if it will also cure other cases of PS intermittency that have cropped up randomly.  Time will tell.

**Comment by RdWing** [comment]
Great, I have been losing PS-A when switching between SSB and CW for at least a year. 
https://community.apache-labs.com/viewtopic.php?f=9&t=4834&p=26895#p26895
Thanks for the hard work.
