### ISSUE TITLE
[FEATURE] Thanks for the IQ SWAP option in v.2.10.2.3-dev branch !

### ISSUE THREAD

**Issue by rsaue** [ramdor/Thetis#227]
Hi Richie, 
Thanks for the add of IQ SWAP option on Direct IQ in VAC menu.

With this add on SDC Skimmer now works with Thetis!

(Sorry for the possible faulty use of the report system. But many users have struggled getting SDC skimmer work along with Thetis.)

73 de LB2EG Richard

**Comment by ramdor** [comment]
no problem. Warren helped out with the WDSP code and I just wired it into the front end. We will look at the RX2 send for IQ option at some point in the future. I made a vid about it the other day, here, https://youtu.be/iQd_E4ffO-w?si=Q8b3aRlCAg_bC7sq

I think you can use the discussion tab at the top of github for things like this afaik.

73

**Comment by Alan5596** [comment]
It may just be me not setting something correctly but I have been unable to get this working successfully in the Hermes Lite 2.  With the new IQ swap checked and spot clicked the tuned frequency is still off.  I wonde if anyone else with a HL2 has it working successfully?
