### ISSUE TITLE
[BUG] CFC Display in DSP > CFC no longer working

### ISSUE THREAD

**Issue by NC3Z** [ramdor/Thetis#231]
**Describe the bug**
Using V2.10.2.2 and notice the CFC graph shows no data and stays black.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings > DSP > CFC
2. Compression display use to show data but now is black/blank

**Desktop (please complete the following information):**
 - OS: Win 11

Do not know which version it went away in.

**Comment by ramdor** [comment]
fixed in dev branch, will be in 2.10.3 when released. Thanks for report.
