### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SM7YES** [ramdor/Thetis#232]
Setup /DSP /CFC shows no spectrum in black window any more. Only black with no moving bars at all when talking, but it appears that CFC-compressor works ok. Just no indications in the specrum bars window. When installing earlier version of Thetis it is ok.
Using Anan 100D.

Thanks
/Per

**Comment by SM7YES** [comment]
I missed to put in right subject instead of "BUG". Sorry but this was my first post ever, here on Github :)

**Comment by NC3Z** [comment]
Ha! Beat you to it!      https://github.com/ramdor/Thetis/issues/231

**Comment by ramdor** [comment]
fixed for next release.
