### ISSUE TITLE
MNF settings lost when a new Thetis version number causes db-reset-and-import

### ISSUE THREAD

**Issue by John-W1JA** [ramdor/Thetis#236]
W2PA often makes his compiled files of new beta version that you create available to me so I too can test it. I overwrite the existing files in my C:\Program Files\OpenHPSDR\Thetis directory. Whenever the version number changes Thetis resets the db and imports the saved version, as expected.

Whenever this happens, I lose all my MNF settings, and have to reconfigure them each time.

The desired behaviour would be for MNF settings to be retained in the above scenario.

**Comment by ramdor** [comment]
Hi John, please include version number of Thetis that is showing this problem. Also include your pre-imported DB, and the DB after the import.

**Comment by John-W1JA** [comment]
Hi Richie. "v2.10.3 x64 (10/29/23)" on title bar; it was compiled by W2PA yesterday.

But, this issue has been present every time the version number has changed for the last month or two. I've been testing most or all of your beta releases along with Chris. And, the issue could have been present even longer; I only started using MNF (it's very useful!) in the last month or two.

[database - pre-import.zip](https://github.com/ramdor/Thetis/files/13208553/database.-.pre-import.zip)
[database - after import.zip](https://github.com/ramdor/Thetis/files/13208555/database.-.after.import.zip)

**Comment by ramdor** [comment]
Thanks John. Yes there was a problem, but should now be resolved.
