### ISSUE TITLE
[BUG] SNB output bandwidth ≠ audio bandpass

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#249]
I suspect that the output bandwidth of the SNB is not being set consistent with the RX audio bandpass.

You can replicate by tuning any signal, set RX bandpass to 0-3000; when engaging SNB you can immediately tell that the low cut has been moved up to 250 Hz.

I tested this by engaging the receive signal generator and first applying a sweep to RX1 and engaging the SNB. Then, I stepped a tone from 100 Hz to 300 Hz. The tone starts being audible around 205 Hz but sounds reduced in amplitude until 250 Hz.

There was a prior method void SetRXASNBAOutputBandwidth (channel, flow, fhigh) that was used for this, but it is marked deprecated in the WDSP guide, having been replaced with RXA Collective RXASetPassband ( ... ) .

Perhaps there is some plumbing that needs to be applied, or perhaps this was a deliberate design decision.

**Comment by ramdor** [comment]
Currently code does this 

![image](https://github.com/ramdor/Thetis/assets/3124967/b326bfb8-4639-4d8a-af4e-ef7a2822d3b0)

which are the same functions included in the collective

![image](https://github.com/ramdor/Thetis/assets/3124967/16a6f666-a1de-4b7c-8a0e-c301ee0179c5)

Perhaps @NR0V Warren has some more info on this?

**Comment by ramdor** [comment]
This is probably the reason why

![image](https://github.com/ramdor/Thetis/assets/3124967/e89cf966-d97e-4522-9c6d-8acabe5f5b31)

**Comment by ramdor** [comment]
email reply from Warren

> It’s absolutely true that the SNB filtering restricts the low-end audio frequency range.  However, this is NOT a bug, it is BY DESIGN.  The SNB cutoff frequencies were very carefully chosen to avoid algorithmic problems and excessive computation that would otherwise occur in certain situations.  This is not because of a bug, it’s just the way the algorithm works.

**Comment by ramdor** [comment]
closing, nothing to be done
