### ISSUE TITLE
[FEATURE] Puresignal AmpView - Show at startup

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#250]
Add a checkbox at the bottom of the PureSignal AmpView display to "Launch at Startup".
Launch AmpView window at startup, recall last position.

I often use the AmpView display and would love to have it auto-launch upon Thetis launch; and without requiring the rest of the PureSignal configuration box to be open.

**Comment by ramdor** [comment]
implemented in 2.10.3.4, to be released in a couple of weeks. Closing.
