### ISSUE TITLE
GUI Locks Up [BUG]

### ISSUE THREAD

**Issue by w2fmu** [ramdor/Thetis#251]
Bug report. When using DX Labs Commander, Thetis 2.10.3 will work fine until the power button on the GUI is clicked. That locks the entire GUI. The only way out is to kill Thetis in Task Manager.
2.10.2.2 worked fine

Widows 10 
Ernie
W2FMU

**Comment by ramdor** [comment]
being worked on, thanks for report

**Comment by ramdor** [comment]
hopefully fixed in the v2.10.3.1 updated release

**Comment by ramdor** [comment]
now resolved

**Comment by w2fmu** [comment]
Thanks Richie!  All good now.
