### ISSUE TITLE
[FEATURE] Allow Active Peak Hold to go beyond 10000ms (10 sec)

### ISSUE THREAD

**Issue by Slossoff** [ramdor/Thetis#253]
**Is your feature request related to a problem? Please describe.**
The current limitation of Active Peak Hold is 10 seconds and is still to short. 

**Describe the solution you'd like**
Allow the Active Peak Hold to be set for something larger than 10 seconds and allow for an infinite peak hold.

**Describe alternatives you've considered**
Only work around I have found is to enable Peak on the main screen, but that also affects the waterfall and not just the spectrum which is problematic when you only wanted to affect the Peak hold line decay timer.

**Comment by ramdor** [comment]
you can set drop to 0.0 to get infinite hold, will increase the time to 1min in future update

**Comment by ramdor** [comment]
2.10.3.4 will see 60 seconds limit, closing
