### ISSUE TITLE
[BUG]Thetis-V2.10.3x64 not able to open. With windows 11

### ISSUE THREAD

**Issue by K2GX** [ramdor/Thetis#254]
![Win 11 Error](https://github.com/ramdor/Thetis/assets/103886621/71af8e2e-3208-46a6-a01a-89dc8f7696c9)
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots
![Win 11 Error](https://github.com/ramdor/Thetis/assets/103886621/4a60ecc7-98ff-406d-a67d-21ec3d0157c9)
**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by ramdor** [comment]
uninstall, reboot pc, re-install. Give that a try.

**Comment by ramdor** [comment]
try https://github.com/ramdor/Thetis/releases/tag/v2.10.3.1

**Comment by ramdor** [comment]
ok, give the latest release a try and let me know how it goes. Thanks.

**Comment by ramdor** [comment]
fixed now
