### ISSUE TITLE
[BUG] 2.10.3.3 Broken MIDI controller

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#255]
Windows 10
Previously in 2.10.2 it was working fine. Tested on 2.10.3.0-2.10.3.3 and it works somewhat. After a small rotation of a midi platter controller, Thetis continues to scroll in frequency up or down while uncommanded. While this is occurring, it locks up the program and the computer. After 10 seconds or so the program will recover, but it will have shifted itself to a different frequency past the desired one.

**Comment by ramdor** [comment]
midi on my hercules djcontrol starlight seems to work ok. Wheel decks move vfo fine. Do you have other cat software connected at the same time?

**Comment by RdWing** [comment]
No, there was no other CAT software connected at the time. I checked with a midi tool to show the output from the platter controller in windows, and it looked ok. However when I checked the midi diagnostics in thetis it showed the command repeating over and over. Downgrading to 2.10.2 resolved the issue.

**Comment by ramdor** [comment]
no clue what that is, zero changes to anything midi in 2.10.3.. hmmm

**Comment by ramdor** [comment]
actually some commands got added, perhaps something happened. Will check it.

**Comment by RdWing** [comment]
Yes, the behavior persisted after a reboot. We reverted to 2.10.2, not 2.10.2.2.
This is not on my machine here, so I will have to test it tomorrow and report back.

**Comment by W2PA** [comment]
I haven't noticed any behavior change with my two Behringer controllers.  What happens when you change the VFO sensitivity? It can be toggled between high and low using the MIDI command "VFO Wheel Sensitivity High/Low Toggle".  The values are set as Min and Max in the Setup-Serial/Network/Midi CAT-MIDI tab.

**Comment by ramdor** [comment]
what needs addressing in midi for at least my controller, is that there are 7 and 14 bit messages from each knob/slider, so the midi ui has a complete crazy moment when all those are coming in, alternating. Virtually impossible to set anything up. I have to use bome midi translator as the 'middle man' to only forward on 7 or 14 bit msgs to thetis via a virtual midi device. Probably not related to this, but worth a comment.

**Comment by RdWing** [comment]
Further testing has not been able to replicate the issue. Close?

**Comment by ramdor** [comment]
yes closing, as I am unable to replicate it. If it is on a different midi deck to the one you are used to, then the 14bit issue might be the problem. Re-check when 2.10.3.4 arrives in a couple of weeks
