### ISSUE TITLE
DirectX Errors in parallels [BUG]

### ISSUE THREAD

**Issue by grabauter** [ramdor/Thetis#258]
**Describe the bug**
Using parallels (Virtualization) on MacOS, from time to time display freezes, and an error popup appears "Problem in DirectX Renderer"

leading to a freeze of thetis and even the whole VM. Suspending and starting again fixes the freeze, after thetis restart everything works fine again.

**To Reproduce**
Not reproducible. Error occurs randomly, but mainly when waterfall is running.

**Expected behaviour**

No directx errors.

**Screenshots**

![image](https://github.com/ramdor/Thetis/assets/45741629/8b8c5a3b-2835-4c88-bf72-9f02f0f75903)

**Desktop (please complete the following information):**
MacOS 13.3.1, Parallels 19 professional

**Additional context**

Never seen this error in vmware or "native" installation on a Windows PC, so might be related to a bug in parallels.

**Comment by ramdor** [comment]
I dont have a mac running parallels so will be impossible for me to reproduce. The first step would be for me to see the message in English.

**Comment by ramdor** [comment]
Thetis isn't supported in any way for this platform. Closing
