### ISSUE TITLE
Locking up

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#260]
**Describe the bug**
V2.10.3 Cat control could  be  the one -- GUI  is non reponse  and CAT control is non-responsive.  Spectrum still being  displayed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Was running FLRig and also a 2nd rigctl instance  connecting to a 2nd COM port (Hamlib testing).

**Expected behaviour**
Not lock up.

 - OS: [e.g. Windows7/8.1/10/11/etc]
 Windows 11 25982.1000

**Comment by ramdor** [comment]
have you tried v2.10.3.3  ??  as you only mention you are using 2.10.3

**Comment by ramdor** [comment]
and no, I am not testing FLrig with it, false positive or not

![image](https://github.com/ramdor/Thetis/assets/3124967/9960f21d-543e-4b64-854c-bfc0a5c7557d)

**Comment by ramdor** [comment]
this is 3 comports in use through VSPE.  WSJTX, DXLabs commander, HRD.  All working fine together when using v2.10.3.3.  In v2.10.3 there were issues due to some locking of the ui.

![image](https://github.com/ramdor/Thetis/assets/3124967/061160a8-8cf5-4e59-9866-f1a675acfefb)

**Comment by mdblack98** [comment]
Oh rats -- was running an older version in my autostart app....

Running 2.10.3.3 now....twas running 2.10.3.3 from my local build without any problem.










On Saturday, November 4, 2023 at 03:49:29 PM CDT, Richie ***@***.***> wrote: 







have you tried v2.10.3.3 ?? as you only mention you are using 2.10.3

**Comment by mdblack98** [comment]
All these virus vendors get false positives on these "generic" detectors.
Unless it's a major vendor or lots of vendors I ignore them.
My Master's degree happens to be in information security.








On Saturday, November 4, 2023 at 04:04:28 PM CDT, Richie ***@***.***> wrote: 







and no, I am not testing FLrig with it, false positive or not

**Comment by ramdor** [comment]
when one is releasing install packets like I am, I have to be 110% sure. It is not worth the risk, The last virus I had was when I first migrated from an Acorn machine, to an Intel P90 and used a magazine cover disk, back in the mid 90's. I learnt my lesson well.
