### ISSUE TITLE
change mode from digiU to cw, then back to digiU, no tx..

### ISSUE THREAD

**Issue by w5xz** [ramdor/Thetis#265]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by ramdor** [comment]
DIGI can use different TX profiles (or can be configure to). Make sure that if you are using different TX profiles for the CW mode and DIGI that the audio driver/input/output devices are set correctly. Also check if you are recovering device vac details if you do indeed use different TX profiles when you switch modes.

![image](https://github.com/ramdor/Thetis/assets/3124967/f6d9b274-b2e9-47d2-84a0-924d8f25aea1)

**Comment by w5xz** [comment]
ok, thanks...will have to study tx profiles...thought that was mostly for various ssb configs...dont use ssb much here..

73, w5xz, dan

**Comment by w5xz** [comment]
Cockpit error, as usual...had to set windows sound devices to 16 bits to match VMB..now all is well..sri for the QRM..

73, w5xz, dan

**Comment by ramdor** [comment]
cheers for the update Dan. cheers, 73. Richie.
