### ISSUE TITLE
[FEATURE] Change Waterfall Display High/Low to change in 5dB increments

### ISSUE THREAD

**Issue by Slossoff** [ramdor/Thetis#267]
**Is your feature request related to a problem? Please describe.**
Under Display > RX1/RX2 > Waterfall the High/Low up and down arrows change in 10dB increments.  

**Describe the solution you'd like**
Change the up and down value operators under Display > RX1 and RX2 > Waterfall the High/Low to change in 5dB increments.

**Describe alternatives you've considered**
The operator must manual enter in the value to get to go in-between (for example 115bB).

Thanks for all the hard work you've already put towards this project. Simply amazing.

**Comment by ramdor** [comment]
has been change for 2.10.3.4
