### ISSUE TITLE
[FEATURE] TX profile safety feature request

### ISSUE THREAD

**Issue by torrenthd** [ramdor/Thetis#272]
Hi Richie,

Could you please add, in a future version, an option to disable the output to the amplifier PTT linked to each the TX profile?

This will be a good option, so we can have a high power profile on Thetis without the possibility of damaging the amplifier by mistake.

Thanks

**Comment by RdWing** [comment]
Hi @torrenthd 
I'm not sure this is actually possible. I would like it to be, to just be software de-selectable wether or not the RCA PTT out line is asserted or not.
However, there is a workaround. You can use the open collector outputs to control external gear, preamps, amplifiers, switches, etc. When I use my tube amp I use Pin 7 on TX to control keying. If you enable xPA for TX Pin 7 you get an extra button you can turn on and off to enable/disable.

**Comment by ramdor** [comment]
it is not possible, as the firmware and/or hardware doesn't support it. We looked at this before I think and decided it was not possible. The only way to do this is to use the OC system as @RdWing mentions. It might be worthwhile storing the xPA button state in the profile though.

**Comment by torrenthd** [comment]
RdWing and ramdor thanks for clarifying it. 
It is really a pitty.

Richie, can I close this issue?

**Comment by ramdor** [comment]
sure
