### ISSUE TITLE
[BUG] Reverse Phase inop

### ISSUE THREAD

**Issue by wa1oxt** [ramdor/Thetis#275]
GOTO : Gen/DSP/CFC/ "Reverse Phase" inop.

Steps to reproduce the behaviour:
1. Go to main GUI,Select "Scope".
2. Click on "MOX".
3. Modulate.
4. Turn Reverse Phase on/off 
5. No change of Microphone Phase.

**Expected behaviour**
Expected it to change Mic phase 180 degrees.

Win 11 23H2
2.10.3.3 , Anan 100D

tnx. Gary/OXT

**Comment by ramdor** [comment]
thanks, wrong call was being made, will be changed for [2.10.3.4] pre-release_3 sometime today/tomorrow

**Comment by wa1oxt** [comment]
Great Tnx...owe you some BUD..That's a Budweiser LOL
regards Richie,
gary /oxt
    On Sunday, November 12, 2023 at 01:03:53 AM EST, Richie ***@***.***> wrote:  
 
 


thanks, wrong call was being made, will be changed for [2.10.3.4] pre-release_3 sometime today/tomorrow

**Comment by ramdor** [comment]
pre-release-3 is up Gary. Give it a try. I am not sure if it has been tested, but the correct WDSP function is being used now to switch it on/off. Let us know how it goes. Cheers !

**Comment by w-u-2-o** [comment]
Please note that the built-in oscilloscope function may not be adequate to determine whether or not reverse phase is working. See: https://community.apache-labs.com/viewtopic.php?f=48&t=4768&p=26136

**Comment by ramdor** [comment]
I didn't observe any change in it when I tested earlier today with scope1. I fixed a small draw issue with scope1 but it didn't resolve those odd artifacts seen in that thread. I didn't look at it in depth however.

**Comment by ramdor** [comment]
interestingly if you use the Test tab, and generate a tone, say 100Hz in RX the trace looks fine. However if the same test is done in TX the trace is all over the place.

**Comment by ramdor** [comment]
Scope fixes

https://youtu.be/wRxkV25XBuY?si=rD614HYMH5ceU3xx

**Comment by w-u-2-o** [comment]
Nice improvement!

**Comment by wa1oxt** [comment]
Hey Scott ,
Just love the support.Still running my HomeBrew 100D 
Thanks to all . 
Enjoy the Holidays.Please pass it forward
73gary
    On Monday, November 13, 2023 at 06:26:44 AM EST, w-u-2-o ***@***.***> wrote:  
 
 


Nice improvement!

**Comment by wa1oxt** [comment]
Rich , Nice work on the Scope .I see the same issue as in your video.Try and put the" Reverse Phase" Switch before the Phase Rotator feature.
Let me start on a clean page..Most voices are Asymmetrical , some have more energy above zero,some more below. Some Microphone  preamps feature a "Phase Switch" that allow swapping pin 1&2 to insure positive pressure on the microphone capsule causes positive voltage output.The goal is to get a "symmetrical" waveform.  An adjustable Phase Rotator( Allpass Filter) will help https://czh-labs.com/audio-all-pass-filter-phase-rotator-module-board-md-a110-audiowind-a-110-p1300.html, matter of fact a " APR" (Adaptive Phase Rotator) would really do the trick !Now we have a more symmetrical waveform (voice) to present the audio processing chain.My Mic Pre has just that switch, and clearly shows phase reversal on the Scope GUI.So maybe before the Phase Rotator will work.
Again , great job on 2.10.3.4.
Cheers,Gary/oxt


    On Monday, November 13, 2023 at 02:39:03 AM EST, Richie ***@***.***> wrote:  
 
 


Scope fixes

https://youtu.be/wRxkV25XBuY?si=rD614HYMH5ceU3xx

**Comment by ramdor** [comment]
hi Gary, I am  not sure where Warren placed the phase reverse code in the pipeline. Hopefully he is following this. I'll drop him a msg.

**Comment by ramdor** [comment]
just had a quick gander at the code, and it does seem that phase is reversed before it goes through the phase rotation process

**Comment by ramdor** [comment]
haha, ooops. Ok found an issue where it wasnt acutally turning it on/off. I will release a pre-release-5 in a while which will include this fix.

**Comment by wa1oxt** [comment]
OK cool, maybe it wants to be the very first feature in the audio chain .

    On Monday, November 13, 2023 at 04:31:26 PM EST, Richie ***@***.***> wrote:  
 
 


just had a quick gander at the code, and it does seem that phase is reversed before it goes through the phase rotation process

**Comment by w-u-2-o** [comment]
Audio processing block diagram follows. The phase rotator makes the reverse phase setting largely redundant.

![34217808844_4ba34553d1_o](https://github.com/ramdor/Thetis/assets/100238155/b987f6b5-1578-45c6-8dd6-15679ac48d1d)

**Comment by wa1oxt** [comment]
most cool..goto love  OM !
    On Monday, November 13, 2023 at 04:39:20 PM EST, Richie ***@***.***> wrote:  
 
 


haha, ooops. Ok found an issue where it wasnt actually turning it on/off. I will release a pre-release-5 in a while which will include this fix.

**Comment by wa1oxt** [comment]
Put Phase Reversal b4 VAC TX Gain ?
    On Monday, November 13, 2023 at 04:49:02 PM EST, w-u-2-o ***@***.***> wrote:  
 
 


Audio processing block diagram follows. The phase rotator makes the reverse phase setting largely redundant.

**Comment by ramdor** [comment]
> Audio processing block diagram follows. The phase rotator makes the reverse phase setting largely redundant.

phase rotator off,  phase reverse on in that case.  They are independent, but the reverse is done, before the phase rotator code, in the same function in wdsp.

**Comment by w-u-2-o** [comment]
Are you saying that one cannot use both functions simultaneously? That the
state of one depends on the state of the other (phase rotator and phase
reversal)?

They ought to be completely independent of one another.

**Comment by ramdor** [comment]
![image](https://github.com/ramdor/Thetis/assets/3124967/fadf227c-e766-4f95-96ec-3c000ab50662)

**Comment by ramdor** [comment]
so yes they can both be on or off, and their state is independent of each other

**Comment by ramdor** [comment]
now closing this, as pre-release-5 is now able to turn this on/off which does actually help ;)

**Comment by wa1oxt** [comment]
Ya Baby.. Works now !tnx
gary
By the way,  MIC Gain slider inop on main GUI using VAC.
    On Monday, November 13, 2023 at 05:24:54 PM EST, Richie ***@***.***> wrote:  
 
 


so yes they can both be on or off, and their state is independent of each other

**Comment by W1AEX** [comment]
"Reverse Phase" in the CFC form is working fine as observed with my bench scope. Thanks!  W1AEX-Rob
