### ISSUE TITLE
[Power meter = 0 during TX]

### ISSUE THREAD

**Issue by StanoA** [ramdor/Thetis#279]
**Describe the bug**
The power meter in upper right corner of Thetis shows "zero" power during TX. The measured power on artificial 50 Ohm load is 6W. The measured "AIN1" and "AIN2" signals from the Filter board don't fit the required level. When measured by scope the scope shows the small positive / negative peaks when TX starts / ends. I wonder about issue in the SWR bridge on the Filter board.

**To Reproduce**
1. Select e.g. 40m band, AM or FM mode, on-board PA enabled, the right output level on the load is set;
2. Click the MQX to activate TX mode;
3. Measure the power signal at the 50 Ohm load (cca 50V peak-peak)
4. See error - the value on the power meter is = 0.

**Expected behavior**
The value on the power meter has to show the proper value in wats (or dBm).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 - 64bit, DELL PC, Hermes connected by 50cm long ETH cable Cat6, Hermes HL2 powered from 12V DC laboratory PS.

**Additional context**

**Comment by ramdor** [comment]
please report on the HL2 fork here :   https://github.com/mi0bot/OpenHPSDR-Thetis

We do not natively support Hermes Lite 2.

**Comment by StanoA** [comment]
Thank you Richie for your suggestion.

Stano.

po 13. 11. 2023 o 21:59 Richie ***@***.***> napísal(a):
