### ISSUE TITLE
Mic Gain Slider .

### ISSUE THREAD

**Issue by wa1oxt** [ramdor/Thetis#281]
**Describe the bug**
No Mic gain change using Mic slider on main GUI using VAC.

**To Reproduce**

1. Go to 'MOX...'
2. Slide Mic gain Increase/decrease
3. No change of mic gain

**Expected behaviour**
Increase/decrease  Mic input gain

Desktop 
 Windows 11 Pro

Anan 100D. 2.10.3.4 pre-release 5 / P2.

tnx/wa1oxt

**Comment by w-u-2-o** [comment]
This is not necessarily a bug. It has worked this way since the dawn of
openHPSDR. It's more of a feature request. It would need to control VAC TX
gain.

**Comment by wa1oxt** [comment]
Worked a long time ago ...maybe 2016 .Well then, let it be a feature request.Should I repost it ?
gary    On Monday, November 13, 2023 at 09:22:16 PM EST, w-u-2-o ***@***.***> wrote:  
 
 

This is not necessarily a bug. It has worked this way since the dawn of
openHPSDR. It's more of a feature request. It would need to control VAC TX
gain.

**Comment by ramdor** [comment]
Linking that to VAC would not be ideal, as there are many areas of the code that use that mic slider. It wouldn't be a very clean solution. It would need an option in setup to say 'mic slider only controls vac gain' or some such.

I just use the vac rx/tx gain values, and as they are per tx profile it is rare they need changing once set

![image](https://github.com/ramdor/Thetis/assets/3124967/40349bfb-9bea-486e-8f5c-31690178d970)

**Comment by wa1oxt** [comment]
I understand.I do the same here 
tnxgary
    On Tuesday, November 14, 2023 at 01:54:59 AM EST, Richie ***@***.***> wrote:  
 
 


Linking that to VAC would not be ideal, as there are many areas of the code that use that mic slider. It wouldn't be a very clean solution. It would need an option in setup to say 'mic slider only controls vac gain' or some such.

I just use the vac rx/tx gain values, and as they are per tx profile it is rare they need changing once set

**Comment by wa1oxt** [comment]
ok tnx
gary
    On Wednesday, November 15, 2023 at 01:32:48 PM EST, Richie ***@***.***> wrote:  
 
 


Closed #281 as completed.
