### ISSUE TITLE
Feture: Option to have Diversity & Setup  come up on Thetis startup

### ISSUE THREAD

**Issue by wa1oxt** [ramdor/Thetis#286]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what new feature you are thinking of.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ramdor** [comment]
may have 'auto start exe's at some point. As for now, there are a bunch of options to set certain forms to show at startup.

![image](https://github.com/ramdor/Thetis/assets/3124967/3fb87d65-bbb9-434f-8cc9-94582f5f3744)
