### ISSUE TITLE
Waterfall colors on 2.10.3.4 [BUG]

### ISSUE THREAD

**Issue by OneOrphan** [ramdor/Thetis#289]
Awkward colors in waterfall when selecting linlog/lingrad/linauto.

<img width="794" alt="Screenshot 2023-11-21 095520" src="https://github.com/ramdor/Thetis/assets/68202217/8d571400-730d-457c-ad53-bcbb5c9086ab">
<img width="559" alt="Screenshot 2023-11-21 100248 1" src="https://github.com/ramdor/Thetis/assets/68202217/c8b7510e-0d9a-41c5-8fd6-91d8352bed00">
<img width="559" alt="Screenshot 2023-11-21 100248" src="https://github.com/ramdor/Thetis/assets/68202217/a0252fc0-4770-4418-b0d2-8353724e57b4">

Kind regards,
Dick - KA5KKT

**Comment by ramdor** [comment]
yes Lin palettes are rgb reversed in 2.10.3.4.  Will be resolved in future update. Thanks for report.

**Comment by OneOrphan** [comment]
Thanks, Richie!


Dick - KA5KKT
