### ISSUE TITLE
Remember AmpView window size [FEATURE]

### ISSUE THREAD

**Issue by nj2us** [ramdor/Thetis#292]
**Is your feature request related to a problem? Please describe.**
In v2.10.3.4 the Ampview window can be resized. However, the new size is not remembered when restarting Thetis.

**Describe the solution you'd like**
Remember the size and position of the AmpView Window

**Describe alternatives you've considered**
Ignore/accept the present behavior

**Additional context**
None

Jeff NJ2US

**Comment by ramdor** [comment]
fixed #295
