### ISSUE TITLE
IQ stream outside of the VAC function

### ISSUE THREAD

**Issue by makidoja** [ramdor/Thetis#299]
Please could the developers look at adding a seperate IQ stream instead of this being in the VAC

I use Thetis with my ANAN7000DLE over the LAN, the Radio is in the shack but I opertae from within the house, this works very well, except I like to use SDC Skimmer to skim local CW spots, this is only acheivable by using the second RX exclusively for a IQ stream, this feels clunky and I really want to use the second RX to watch other bands.

So having the VAC1 for RX1 and VAC2 for RX2 is great but having the IQ stream as a seperate option outside of the VAC would be amazing!

Thanks for all the hard work and support of Thetis, it's a great tool!

Jim M0CKE - G7C

**Comment by ZipDriver** [comment]
Fully agree with Jim. Will be great to have IQ streams separate from VAC functionality.

Andy - YL2QN

**Comment by ramdor** [comment]
I see from the cmASIO thread over on the Apache-Labs forums that you are using that new feature to free up the vacs for your IQ streams.
