### ISSUE TITLE
Turning the loudspeaker on and off

### ISSUE THREAD

**Issue by RU6AI** [ramdor/Thetis#308]
Please, if possible, add the option Turn on/off the built-in speaker. Audio - Options - Disable audio amplifier.
Either on the front panel or on the Midi remote control.

**Comment by ramdor** [comment]
new features added. Will be in dev_5

- [add] zzxa cat command to get/set audio amplifier (rear speaker sockets). zzxa1; to enable, zzxa0; to disable
- [add] midi button command to toggle audio amplifier (rear speaker sockets)
