### ISSUE TITLE
[BUG]il mio rimane sempre quello TX errore display (DUP + PS-A + CTUN) se tolgo  (PS-A) funziona ok ma non credo che sia corretto Grazie

### ISSUE THREAD

**Issue by iw8rvqtony** [ramdor/Thetis#309]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by oe3ide** [comment]
??? what is your problem?

**Comment by iw8rvqtony** [comment]
mine always remains the TX display error (DUP + PS-A + CTUN) if I remove
(PS-A) it works ok but I don't think it is correct Thanks

Il giorno gio 30 nov 2023 alle ore 22:34 Richie ***@***.***>
ha scritto:

**Comment by ramdor** [comment]
yes, you have reported this MANY MANY times already on the HL2 repo.  It is already known about and it is NOT high on my priority list to fix it as it.  If you continue to spam this repo with the same report then I will remove your ability to report things.

The original issue is here : https://github.com/ramdor/Thetis/issues/215   and will be fixed when I feel like looking at it.
