### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#312]
**Describe the bug**
During git pull VersionInfo.cs has problems with merging.

**To Reproduce**
Steps to reproduce the behaviour:
1. Git pull on Thetis github 
2. Notice merge conflict

**Expected behaviour**
No merge conflice

**Screenshots**

**Additional context**
Since this file is created during build it does not need to be in the git repository.

**Comment by ramdor** [comment]
I want to have it included in the release archive zips so it stays.  Users that are forking from this and then having issues show up because this master is ahead of their VersionInfo.cs need to use syncfork or some such.

**Comment by mdblack98** [comment]
Color me confused...why does it need to be in the release archive when it's created as you compile the solution?


On Friday, December 1, 2023 at 06:13:49 PM CST, Richie ***@***.***> wrote: 







I want to have it included in the release archive zips so it stays. Users that are forking from this and then having issues show up because this master is ahead of their VersionInfo.cs need to use syncfork or some such.

**Comment by ramdor** [comment]
because the archive zips should be representative of what when into the release exe? and it doesn't matter that it is there?

**Comment by ramdor** [comment]
I got frustrated with having to update titlebar.cs each time I sent out a test build which is why I implemented the pre-build event for it.

As a test I just cloned the whole repo, started from scratch, and whilst the file does change each new day obviously if you compile it and consequently is included in any push, why does that actually matter? It is certainly easier to read the .cs file in the repo rather than having to inspect the pre-build event command line stuff.

Without VersionInfo.cs being included in the source files where we referenced in titlebar.cs we would need to go poking around with the following just to uncover what VersionInfo.BuildDate does.

```
@echo off
for /f "delims=" %%x in ('wmic os get localdatetime ^| find "."') do set datetime=%%x
set year=%datetime:~2,2%
set month=%datetime:~4,2%
set day=%datetime:~6,2%
set formatted_date=%month%/%day%/%year%

echo // >  "$(ProjectDir)VersionInfo.cs"
echo //Auto Generated Pre-Build event MW0LGE >> "$(ProjectDir)VersionInfo.cs"
echo // >>  "$(ProjectDir)VersionInfo.cs"
echo using System; >> "$(ProjectDir)VersionInfo.cs"
echo namespace Thetis >> "$(ProjectDir)VersionInfo.cs"
echo { >> "$(ProjectDir)VersionInfo.cs"
echo     public static class VersionInfo >> "$(ProjectDir)VersionInfo.cs"
echo     { >> "$(ProjectDir)VersionInfo.cs"
echo         public static string BuildDate { get { return "%formatted_date%"; } }  >> "$(ProjectDir)VersionInfo.cs"
echo     } >> "$(ProjectDir)VersionInfo.cs"
echo } >> "$(ProjectDir)VersionInfo.cs"
```

**Comment by ramdor** [comment]
and just to add, you could use a local git index update to assume the file is unchanged in your local

**Comment by ramdor** [comment]
hmm well that didnt work. Not sure how to tell my local git not to push changes to that file. If I git ignore it and remove from repo the compile fails as it is not part of the vs project. The file is created as part of the pre-compile-event but it is not auto added to the project so it fails. I am not sure --assume-unchanged will help in this case for everyone that pulls the repo.  Any ides Mike?

**Comment by W4WMT** [comment]
I just do a git checkout -- */VersionInfo.cs and it goes away after a build.
I've done it so often that I don't even think about it anymore  :-)
