### ISSUE TITLE
0Hz signal and buzz noise 

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis#314]
**Describe the bug**
No antenna connections....one can hear a "buzz" frequently when doing nothing else.
This is audible when gain is max and Master AF max.  NR2 and SNB don't make much difference.

**To Reproduce**
Steps to reproduce the behaviour:
1. Disconnect antennas
2. Increase Gain to 120
3. Increase Master AF to max
4. Tune to 1KHz to see 0Hz spike -- buzz is audible everywhere.

**Expected behaviour**
0Hz should be zero (no such thing as 0Hz)
No buzzing

**Screenshots**
Video here
https://www.dropbox.com/scl/fi/mrpzv7jtoaoyprduyj79q/Recording-2023-12-03-081113.mp4?rlkey=ih3ijv5v83jaf2imnwbibnt2x&dl=0

**Desktop (please complete the following information):**
 - Windows 11 Canary build

**Additional context**
The 0Hz has been going on for a while -- I was doing some testing without the antennas connected and noticed this.  The buzz, albeit low-level would affect decoding of FT8 signals for example as the noise floor is moving.

**Comment by ramdor** [comment]
Ah interesting that buzz. If no antenna etc connected then it has to be quite strong somewhere. It reminded me of my aprs 144.800MHz packets from my aprs gateway overloading the front end of other 2m rigs here.

ref the 0Hz thing, cheers for the info. The 0Hz thing has been there for a long long time, so is it that important? Perhaps Warren can look at it if he has the time. This screen shot is from the 4th March 2017 version, 2.3.11 :

![image](https://github.com/ramdor/Thetis/assets/3124967/441fe8e6-760b-4238-8ebe-03d61c27e65c)

**Comment by mdblack98** [comment]
Here's something interesting -- I zeroed out the DC offset in two places that I could find.And now I'm picking up voice audio.....and the amplitude showing at 0Hz has decreased considerably but not gone completely (as I would expect it to gone).  Maybe this explains the noise I'm hearing during the daytime.Why would ANY AM received station show up at 0Hz?  Something fishy going on here....
https://www.dropbox.com/scl/fi/gtzoe6sxf1m60t8n54evt/Recording-2023-12-03-230854.mp4?rlkey=196h1sibp4bazae49xopzkp44&dl=0


diff --git a/Project Files/Source/wdsp/cfcomp.c b/Project Files/Source/wdsp/cfcomp.cindex 99dd858..7404844 100644--- a/Project Files/Source/wdsp/cfcomp.c+++ b/Project Files/Source/wdsp/cfcomp.c@@ -181,6 +181,8 @@ void calc_cfcomp(CFCOMP a)        a->Rfor = fftw_plan_dft_r2c_1d(a->fsize, a->forfftin, (fftw_complex *)a->forfftout, FFTW_ESTIMATE);        a->Rrev = fftw_plan_dft_c2r_1d(a->fsize, (fftw_complex *)a->revfftin, a->revfftout, FFTW_ESTIMATE);        calc_cfcwindow(a);+       a->forfftout[0].re = 0.0;+       a->forfftout[0].im = 0.0;
        a->pregain  = (2.0 * a->winfudge) / (double)a->fsize;        a->postgain = 0.5 / ((double)a->ovrlp * a->winfudge);diff --git a/Project Files/Source/wdsp/emnr.c b/Project Files/Source/wdsp/emnr.cindex cf22871..452fb1c 100644--- a/Project Files/Source/wdsp/emnr.c+++ b/Project Files/Source/wdsp/emnr.c@@ -249,7 +249,8 @@ void calc_emnr(EMNR a)        a->Rfor = fftw_plan_dft_r2c_1d(a->fsize, a->forfftin, (fftw_complex *)a->forfftout, FFTW_ESTIMATE);        a->Rrev = fftw_plan_dft_c2r_1d(a->fsize, (fftw_complex *)a->revfftin, a->revfftout, FFTW_ESTIMATE);        calc_window(a);-+       a->forfftout[0].re = 0.0;+       a->forfftout[0].im = 0.0;        a->g.msize = a->msize;        a->g.mask = a->mask;        a->g.y = a->forfftout;


 

    On Sunday, December 3, 2023 at 10:45:10 PM CST, Richie ***@***.***> wrote:  
 
 


Ah interesting that buzz. If no antenna etc connected then it has to be quite strong somewhere. It reminded me of my aprs 144.800MHz packets from my aprs gateway overloading the front end of other 2m rigs here.

ref the 0Hz thing, cheers for the info. The 0Hz thing has been there for a long long time, so is it that important? Perhaps Warren can look at it if he has the time. This screen shot is from the 4th March 2017 version, 2.3.11 :

image.png (view on web)

**Comment by mdblack98** [comment]
Plain text this time....

 

    On Sunday, December 3, 2023 at 11:17:07 PM CST, Black Michael ***@***.***> wrote:  
 
 Here's something interesting -- I zeroed out the DC offset in two places that I could find.And now I'm picking up voice audio.....and the amplitude showing at 0Hz has decreased considerably but not gone completely (as I would expect it to gone).  Maybe this explains the noise I'm hearing during the daytime.Why would ANY AM received station show up at 0Hz?  Something fishy going on here....
https://www.dropbox.com/scl/fi/gtzoe6sxf1m60t8n54evt/Recording-2023-12-03-230854.mp4?rlkey=196h1sibp4bazae49xopzkp44&dl=0


diff --git a/Project Files/Source/wdsp/cfcomp.c b/Project Files/Source/wdsp/cfcomp.cindex 99dd858..7404844 100644--- a/Project Files/Source/wdsp/cfcomp.c+++ b/Project Files/Source/wdsp/cfcomp.c@@ -181,6 +181,8 @@ void calc_cfcomp(CFCOMP a)        a->Rfor = fftw_plan_dft_r2c_1d(a->fsize, a->forfftin, (fftw_complex *)a->forfftout, FFTW_ESTIMATE);        a->Rrev = fftw_plan_dft_c2r_1d(a->fsize, (fftw_complex *)a->revfftin, a->revfftout, FFTW_ESTIMATE);        calc_cfcwindow(a);+       a->forfftout[0].re = 0.0;+       a->forfftout[0].im = 0.0;
        a->pregain  = (2.0 * a->winfudge) / (double)a->fsize;        a->postgain = 0.5 / ((double)a->ovrlp * a->winfudge);diff --git a/Project Files/Source/wdsp/emnr.c b/Project Files/Source/wdsp/emnr.cindex cf22871..452fb1c 100644--- a/Project Files/Source/wdsp/emnr.c+++ b/Project Files/Source/wdsp/emnr.c@@ -249,7 +249,8 @@ void calc_emnr(EMNR a)        a->Rfor = fftw_plan_dft_r2c_1d(a->fsize, a->forfftin, (fftw_complex *)a->forfftout, FFTW_ESTIMATE);        a->Rrev = fftw_plan_dft_c2r_1d(a->fsize, (fftw_complex *)a->revfftin, a->revfftout, FFTW_ESTIMATE);        calc_window(a);-+       a->forfftout[0].re = 0.0;+       a->forfftout[0].im = 0.0;        a->g.msize = a->msize;        a->g.mask = a->mask;        a->g.y = a->forfftout;


 

    On Sunday, December 3, 2023 at 10:45:10 PM CST, Richie ***@***.***> wrote:  
 
 


Ah interesting that buzz. If no antenna etc connected then it has to be quite strong somewhere. It reminded me of my aprs 144.800MHz packets from my aprs gateway overloading the front end of other 2m rigs here.

ref the 0Hz thing, cheers for the info. The 0Hz thing has been there for a long long time, so is it that important? Perhaps Warren can look at it if he has the time. This screen shot is from the 4th March 2017 version, 2.3.11 :

image.png (view on web)

**Comment by mdblack98** [comment]
Arrghhh....one more attempt at plain text.

On Sunday, December 3, 2023 at 11:18:40 PM CST, Black Michael ***@***.***> wrote:


Plain text this time....


On Sunday, December 3, 2023 at 11:17:07 PM CST, Black Michael ***@***.***> wrote: 





Here's something interesting -- I zeroed out the DC offset in two places that I could find.
And now I'm picking up voice audio.....and the amplitude showing at 0Hz has decreased considerably but not gone completely (as I would expect it to gone).  Maybe this explains the noise I'm hearing during the daytime.
Why would ANY AM received station show up at 0Hz?  Something fishy going on here....

https://www.dropbox.com/scl/fi/gtzoe6sxf1m60t8n54evt/Recording-2023-12-03-230854.mp4?rlkey=196h1sibp4bazae49xopzkp44&dl=0


diff --git a/Project Files/Source/wdsp/cfcomp.c b/Project Files/Source/wdsp/cfcomp.c
index 99dd858..7404844 100644
--- a/Project Files/Source/wdsp/cfcomp.c
+++ b/Project Files/Source/wdsp/cfcomp.c
@@ -181,6 +181,8 @@ void calc_cfcomp(CFCOMP a)
        a->Rfor = fftw_plan_dft_r2c_1d(a->fsize, a->forfftin, (fftw_complex *)a->forfftout, FFTW_ESTIMATE);
        a->Rrev = fftw_plan_dft_c2r_1d(a->fsize, (fftw_complex *)a->revfftin, a->revfftout, FFTW_ESTIMATE);
        calc_cfcwindow(a);
+       a->forfftout[0].re = 0.0;
+       a->forfftout[0].im = 0.0;

        a->pregain  = (2.0 * a->winfudge) / (double)a->fsize;
        a->postgain = 0.5 / ((double)a->ovrlp * a->winfudge);
diff --git a/Project Files/Source/wdsp/emnr.c b/Project Files/Source/wdsp/emnr.c
index cf22871..452fb1c 100644
--- a/Project Files/Source/wdsp/emnr.c
+++ b/Project Files/Source/wdsp/emnr.c
@@ -249,7 +249,8 @@ void calc_emnr(EMNR a)
        a->Rfor = fftw_plan_dft_r2c_1d(a->fsize, a->forfftin, (fftw_complex *)a->forfftout, FFTW_ESTIMATE);
        a->Rrev = fftw_plan_dft_c2r_1d(a->fsize, (fftw_complex *)a->revfftin, a->revfftout, FFTW_ESTIMATE);
        calc_window(a);
-
+       a->forfftout[0].re = 0.0;
+       a->forfftout[0].im = 0.0;
        a->g.msize = a->msize;
        a->g.mask = a->mask;
        a->g.y = a->forfftout;









On Sunday, December 3, 2023 at 10:45:10 PM CST, Richie ***@***.***> wrote: 







Ah interesting that buzz. If no antenna etc connected then it has to be quite strong somewhere. It reminded me of my aprs 144.800MHz packets from my aprs gateway overloading the front end of other 2m rigs here.

ref the 0Hz thing, cheers for the info. The 0Hz thing has been there for a long long time, so is it that important? Perhaps Warren can look at it if he has the time. This screen shot is from the 4th March 2017 version, 2.3.11 :

image.png (view on web)

**Comment by RdWing** [comment]
I cannot reproduce that here, also I'm struck at just how high your noise floor is there...
I checked an on the 7000 DLE Mk2.5 I definitely have a 0hz spike, but I don't hear anything there. If you're hearing AM then I suggest you may have some AM coming in on your DC supply maybe, or something else has a corroded joint.

**Comment by ramdor** [comment]
I can not reproduce this, and as no updates since 10Dec23, I will close. Please re-open with more findings if still a concern.

**Comment by mdblack98** [comment]
I am Apache-less right now -- sold my 7000 -- which did NOT survive being shipped and I sold it for parts for $400 to the maintenance dude who said it was beyond economical repair (:-(....waiting for the ANAN-G2-1K to ship that I've had on order forever and I'll test this again.
