### ISSUE TITLE
panelModeSpecific mislocated

### ISSUE THREAD

**Issue by DH1KLM** [ramdor/Thetis#325]
**Describe the bug**
panelModeSpecific is mislocated after returning to "Expand". Tried with fresh database.

Looks like this issue was already on 2.10.3.4

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'Collapse'
2. Click on 'RX2' (on)
3. Click on 'Expand'
4. now panelModeSpecific is mislocated
5. Click again on 'RX2' (off)
6. Click again on 'RX2' (on)
7. now panelModeSpecific is where it's supposed to be.

![image](https://github.com/ramdor/Thetis/assets/27503182/9c3a88e4-e962-4569-b4b7-bd2523874a85)

**Comment by ramdor** [comment]
followed you reproduce steps to the letter, can't reproduce

https://youtu.be/cHwPJer6VTU

**Comment by ramdor** [comment]
https://youtu.be/spUcQLOpEvQ

**Comment by DH1KLM** [comment]
Checked it right now again. It only occurs in fullscreen mode. If Thetis windows is resized it works as expected.

![image](https://github.com/ramdor/Thetis/assets/27503182/9923efa7-16df-434b-b1b7-febcebc9210e)
![image](https://github.com/ramdor/Thetis/assets/27503182/9f3e6022-9ba4-4351-8032-1a44537dbaff)

**Comment by DH1KLM** [comment]
> cheers, will look at this for next pre-release-3 sometime next week

hihi "pre-release-3 sometime next week". Thats a good one.

You bring us more presents than Santa Claus.

Thanks Santa

**Comment by DH1KLM** [comment]
hihi "pre-release-3 sometime next week". Thats a good one.

Its working.

You bring us more presents than Santa Claus.

Thanks Santa
