### ISSUE TITLE
[BUG] Error when launching Thetis 2.10.3.5 pre 1

### ISSUE THREAD

**Issue by torrenthd** [ramdor/Thetis#326]
Got an error on start up:

![Thetis_error](https://github.com/ramdor/Thetis/assets/114567653/bfeb7ce1-f024-4d3f-a2ab-f536dee3230c)

**Comment by torrenthd** [comment]
Done!

**Comment by ramdor** [comment]
were you running 2.10.3.4 before?

**Comment by mdblack98** [comment]
And here's my database too which is failing -- zeroed it out and I can startup again.
[database.txt](https://github.com/ramdor/Thetis/files/13619832/database.txt)

**Comment by torrenthd** [comment]
> were you running 2.10.3.4 before?

Yes, using 2.10.3.4

**Comment by ramdor** [comment]
ok, pre-release-2 just updated, can you give it a test? cheers.

**Comment by torrenthd** [comment]
Working fine!

Thanks a lot Richie!

**Comment by mdblack98** [comment]
release-2 still fails here with my database (provided earlier)
![image](https://github.com/ramdor/Thetis/assets/8899915/22478e2d-8908-4e48-980b-e5d6dcf328be)

**Comment by ramdor** [comment]
Looks like it is a different issue Mike. Can you replace your Thetis.exe with the one from inside this zip, and test? Cheers.

[Thetis.zip](https://github.com/ramdor/Thetis/files/13621126/Thetis.zip)

https://www.virustotal.com/gui/file/5aacd490ae11560e324747c2f7e3e155edf8cab7056d73cf39f06248d7ab583c?nocache=1

**Comment by mdblack98** [comment]
That one works.....thanks...

 

    On Friday, December 8, 2023 at 03:40:26 PM CST, Richie ***@***.***> wrote:  
 
 


Looks like it is a different issue Mike. Can you replace your Thetis.exe with the one from inside this zip, and test? Cheers.

Thetis.zip

https://www.virustotal.com/gui/file/5aacd490ae11560e324747c2f7e3e155edf8cab7056d73cf39f06248d7ab583c?nocache=1

**Comment by martienverbeek** [comment]
I was using 2.10.3.5 beta 1 before, now with start using 2.10.3.5 beta 2 I get another error message  
![image](https://github.com/ramdor/Thetis/assets/59423080/10c01c15-17fb-4e75-b8c7-1bbf0195d8b5)
[
![Screenshot 2024-04-18 182607](https://github.com/ramdor/Thetis/assets/59423080/0bd32889-b4fc-4a4f-b44e-f9810005029e)
](url)

**Comment by ramdor** [comment]
> I was using 2.10.3.5 beta 1 before, now with start using 2.10.3.5 beta 2 I get another error message

This is not the same issue. Also, please do not go adding duplicates to other **CLOSED** issue/bug reports. You have already created a bug issue report #422 , with the same screenshot. It is a HL2 specific issue, and probably best posted over on the HL2 fork ( oh, it already is.... https://github.com/mi0bot/OpenHPSDR-Thetis/issues/59 ).

**Comment by Aleziss** [comment]
[Here also](https://github.com/mi0bot/OpenHPSDR-Thetis/issues/52#issuecomment-2014892206)
