### ISSUE TITLE
Recording audio playback

### ISSUE THREAD

**Issue by kd4jm** [ramdor/Thetis#329]
Thetis V2.10.3.5 pre-release -3

When you record you own audio using the Microphone plugged in directly into radio "no vac" the audio sound distorted when playing back the recording.

Thanks.

**Comment by ramdor** [comment]
I don't have a cable made up to test this. I only connect RF/power/ethernet connect to my radio.

A) what radio model
B) what firmware
C) protocol?
D) which version of Thetis did you first notice this happening?  This implies that it works fine before the version you list.

Are you able to go back and test older versions of Thetis, back to 2.9.0.8 perhaps?  Only do this if you are comfortable doing this.

**Comment by ramdor** [comment]
can you slide RX1 AF slider to max, and do a record/playback

**Comment by kd4jm** [comment]
I set the RX1 AF 100% like you requested and now it works fine.

**Comment by ramdor** [comment]
ok thanks for that test. Will take a while to resolve that, but at least a work around for now.

**Comment by kd4jm** [comment]
Again, thank you so much for your help.

**Comment by ramdor** [comment]
Hey Jorge, I just want to check something.  Are you recording your own audio from the mic connected to your radio when Thetis is in DUP mode?  Does this work when DUP is off? Cheers.

**Comment by kd4jm** [comment]
Hey Richie,

 Yes I'm recording my own audio with mic connected to radio, I tried the DUP on and off and made no difference.

Cheers.


Jorge M.

**Comment by ramdor** [comment]
should be fixed when 2.10.3.5 pre-release-4 is available. Will leave open for testing/reports.

**Comment by kd4jm** [comment]
Thanks...

**Comment by ramdor** [comment]
> Thanks...

I just released the pre-release-4 if you want to give it a try.

**Comment by kd4jm** [comment]
Richie,
It's working great now, with the pre-release-4. You are the Man.

Cheers.
