### ISSUE TITLE
[BUG] MultiRX/SubRX not working

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#334]
Thetis 2.10.3.5 Prelease 3

MultiRX seems to be stuck on the same frequency as the main VFO. Changing VFO A seems to change VFO B frequency at the same time. Changing VFO B changes VFO A.

When engaging RX2, the same behavior is seen. Even when SD is disabled, changing VFO A changes RX2.

This seems to be related to VFO Sync in the Diversity reception menu.

**Comment by ramdor** [comment]
do you have qsplit on with a 0 offset?

**Comment by ramdor** [comment]
or vfo sync?

**Comment by RdWing** [comment]
Yes I hit the VFO Sync button in the diversity menu the other day, I don't seem to have a way to turn that off. 
I don't have QSPLIT enabled.

I tested this on another machine and after hitting VFO Sync it has the same behavior, can't seem to cancel it.

**Comment by ramdor** [comment]
vfo sync in diversity does infact turn vfo sync on yes, so both vfos will be the same. Sorry for the multiple replies. I can change the vfo sync button in diversity I guess to be off/on state to reflect vfo sync button state.

click the vfo sync button here to turn it off.

![image](https://github.com/ramdor/Thetis/assets/3124967/1ad5bd0c-df1d-452e-902f-596ff5d9aaa6)

**Comment by RdWing** [comment]
That was it, thanks. I agree making the button in diversity menu on/off with an indicator is a great idea.
