### ISSUE TITLE
[BUG] Unable to record and playback TX audio.

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#335]
Thetis 2.10.3.5 prerelease 3 and 4.

Attempting to record transmissions and listen to them and play them back is not working at all. Confirmed across multiple operators.

**Comment by ramdor** [comment]
more info required.

Are you recording transmission, or received signals?
Which record method are you using. QuickRec from console UI, or Record or QuickRec from Wave form?
Are you using VAC?
Is MUT enabled?
Is RX1 af set to 0?

**Comment by RdWing** [comment]
Recording transmission.
QuickRec from console UI.
VAC for both receive and transmit, and "Bypass VAC for recording playback" is checked.
MUT not enabled.
RX1 AF set to 50 (but I believe this is not relevant anymore i.e. normalized).

When I try recording a transmission, whatever plays back is not my mic audio.

[SDRQuickAudio.zip](https://github.com/ramdor/Thetis/files/13682030/SDRQuickAudio.zip)

**Comment by ramdor** [comment]
has this ever worked? I just went back to 2.6.7 (May 2019) and it doesn't via vac. Can you tell me what version this worked with?

**Comment by RdWing** [comment]
It has definitely worked before. I will check the versions. I remember this working recently.

**Comment by rockyjones** [comment]
Record of transmitted audio works fine for me and always has EXCEPT if using CTUN.  It doesn't work then (or hasn't in the past - I haven't checked in a while).  To make it work, the Wave Options must be set to the following;

When Transmitting, 
Transmitter Output I/Q should be selected.  I run Bit Depth of 32-bit IEEE Floats and Sample rate of 48000.  Dither ON and numeric setting below Dither set to 0.8.

Joe W4WT

**Comment by ramdor** [comment]
@rockyjones  Thanks Joe, it did indeed work, recording my TX audio from vac by setting the TX output IQ

![image](https://github.com/ramdor/Thetis/assets/3124967/5f5bdc40-c7c1-4a1f-9b7f-ff1e51e1bb48)

**Comment by RdWing** [comment]
Recording TX **audio** has always worked fine, even with CTUN. I have used it many times in the past.

Recording TX **I/Q** is not the same thing. It seems maybe that selecting Transmitter Output I/Q is now recording TX audio, because it doesn't seem to be taking an I/Q recording.

**Comment by rockyjones** [comment]
RdWing, please let me know the steps you used to make it record with CTUN selected.

Thanks, Joe W4WT

**Comment by RdWing** [comment]
I feel like this is getting a little off track.

The bug is specifically that recording TX audio is now not working. Recording TX I/Q continues to work, but is not the same thing. I double checked that when "Record Transmitter Output I/Q" is selected, it is actually recording the output I/Q files and not the MIC audio stream as intended.

I remember last using this feature (Record/Play MIC) about a month or two ago. @rockyjones I always use CTUN and have always used VAC, and its always just worked. For what's it's worth, I usually use 16-bit/24 kHz format with dither enabled.

This is a critical feature, especially for users setting up audio. (Think recording a basic mic stream and playing it back on loop into a dummy load while adjusting the EQ and CFC in Thetis).

**Comment by ramdor** [comment]
> I remember last using this feature (Record/Play MIC) about a month or two ago. @rockyjones I always use CTUN and have always used VAC, and its always just worked. For what's it's worth, I usually use 16-bit/24 kHz format with dither enabled.

Please spend the time to find a version that worked.  I just spent 20 mins doing that, testing back to 2.6.7 from early 2019. You can watch the testing as I recorded the process. The tldw; is that the recorded wavs from vac are silent unless that option is selected. There may be something we are missing, who knows. Is it a possibility that you unknowingly had that option selected, and now do not ?

https://youtu.be/OeNoUucC10g

Note: there is indeed a phase shift of 90' between left/right channels in the recording.

**Comment by Aleziss** [comment]
> Note: there is indeed a phase shift of 90' between left/right channels in the recording.
I feel the same way when I use the MON function in SSB, while TX, it sounds out of phace also in headphones. AM sounds fine with no out of phase audio. Older version of PowerSDR 3.4.9 sounded fine when monitoring in SSB. I wonder if it has anything to do with your comment also... Thanks !

**Comment by RdWing** [comment]
> > I remember last using this feature (Record/Play MIC) about a month or two ago. @rockyjones I always use CTUN and have always used VAC, and its always just worked. For what's it's worth, I usually use 16-bit/24 kHz format with dither enabled.
> 
> Please spend the time to find a version that worked. I just spent 20 mins doing that, testing back to 2.6.7 from early 2019. You can watch the testing as I recorded the process. The tldw; is that the recorded wavs from vac are silent unless that option is selected. There may be something we are missing, who knows. Is it a possibility that you unknowingly had that option selected, and now do not ?
> 
> https://youtu.be/OeNoUucC10g
> 
> Note: there is indeed a phase shift of 90' between left/right channels in the recording.

Hi, yes, there is a phase shift because its I & Q and not the mic audio. These are not the same things.

I realize what happened. I was running G7KLJ's fork for awhile, and this bug must have been resolved later on in that development branch because Mic Audio recording was still broken in 31a. I have binaries where its working but no source.

https://github.com/ramdor/Thetis/assets/19214916/e6203475-6e45-4fc5-a191-6740be073dd0

I checked back to 2.9.0.8 of this branch and its definitely broken. I'll go back some more and update if I find a working one.

Sorry for the goose chase. Maybe it gets fixed, maybe not. Would be great if it could. Happy to help if I can.

**Comment by rockyjones** [comment]
@RdWing I have full source for Steve's version 2.9.0 on 4/3/2023 if you would like it.  I can provide the whole thing or just a source file for anyone insterested.  I'm going to build and install it tonight, when I have time, to test it for recording audio.

Joe, W4WT

**Comment by ramdor** [comment]
a snapshot of Steve's was made by Scott here : https://github.com/w-u-2-o/Thetis-2.9.0

**Comment by RdWing** [comment]
Yeah the fix happened some time after that version.

**Comment by ramdor** [comment]
afaik that was just before the repo went private, Scott managed to grab a copy I think. v2.9.0.31

**Comment by RdWing** [comment]
> Mic Audio recording was still broken in 31a. I have later binaries where its working but no source.

**Comment by ramdor** [comment]
@RdWing please try https://github.com/ramdor/Thetis/releases/tag/v2.10.3.6-dev

**Comment by Aleziss** [comment]
Thanks for the hard work !

Happy new year !

Claude



Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :30 décembre 2023 13:55
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [ramdor/Thetis] [BUG] Unable to record and playback TX audio. (Issue #335)


@RdWing<https://github.com/RdWing> please try https://github.com/ramdor/Thetis/releases/tag/v2.10.3.6-dev

**Comment by RdWing** [comment]
> @RdWing please try https://github.com/ramdor/Thetis/releases/tag/v2.10.3.6-dev

It works!! What this allows you to do, is record your raw mic signal using the WAV menu. Mox, then play it back on a loop with the PA disabled, and turn on the monitor. Now, you can adjust the EQ's and CFC and everything and hear it live. I tested back to back with a version where it was working, and everything is working as expected.
