### ISSUE TITLE
[FEATURE] Audio over TCI

### ISSUE THREAD

**Issue by makidoja** [ramdor/Thetis#337]
**Is your feature request related to a problem? Please describe.**
Transport of audio to other software without the disruption of the VAC for listener

**Describe the solution you'd like**
Audio over TCI for use by SDC skimmer (CW & RTTY)

**Describe alternatives you've considered**
IQ but this uses VAC and makes VAC useless for listeners audio

**Additional context**
Another option would be additional VACs for IQ use, leaving a VAC for the listeners audio.

**Comment by ramdor** [comment]
duplicated, yet again, from #6
