### ISSUE TITLE
[BUG] Scope timebase during TX different than during RX

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#338]
2.10.3.5 pre-release 4

I have the Scope Mode Time (us) set to 10,000.

Set the display to Panascope or Scope and you'll notice the TX scope seems to run at about twice the speed of the receive display.

https://youtu.be/eNGyGhcvC4k

**Comment by ramdor** [comment]
changes for pre-rel-5. I will probably change from us to ms for that setting

https://youtu.be/jAVP_vLbJ4E
