### ISSUE TITLE
Incorrect meter scale for Estimated PBSNR

### ISSUE THREAD

**Issue by s-car-go** [ramdor/Thetis#348]
The meter scale for the "Estimated PBSNR" shows DB when it is set to show S units.

When you left click on the PBSNR meter it changes the label from DB to SU. However the scale does not change.

![2023-12-19 06_43_47-Thetis Meter  12956](https://github.com/ramdor/Thetis/assets/108140151/d5eee70e-5e7b-487b-8812-f56bc84d4873)

Desktop Windows 10 Pro

Thanks Dave...

**Comment by ramdor** [comment]
Nope it doesn't Dave. The same can be said for the signal meters as the scale doesn't change when you swap from Suntis/uV/dBm.  Clicking on it just changes the text units.  I wont be doing anything about this.

**Comment by s-car-go** [comment]
OK thanks.
