### ISSUE TITLE
Correction of the operation of the switchable attenuator 0-20 dB

### ISSUE THREAD

**Issue by RA4UKL** [ramdor/Thetis#349]
The Hermes Lite transceiver with a switchable attenuator of 0-20 dB does not switch when the attenuation value in the ATT parameter ("attenuation") changes. Changing the AT <-> SAT setting has no effect. Switching works only after resetting the database (the "Reset database" button in the settings) or when changing the "Radio Model" to "H/W Select". After restarting the program, the problem occurs again. The problem has occurred since version 2.9.***

**Comment by ramdor** [comment]
This is the master branch of Thetis for the Apache Labs range of radios. You will need to report this issue on the Hermes Lite branch.
