### ISSUE TITLE
picRX2Squelch does not change from red to green

### ISSUE THREAD

**Issue by DH1KLM** [ramdor/Thetis#356]
picRX2Squelch does not change from red to green like it is for picSquelch in main RX.
Picture shows RX1+2 squelch on same band and frequency acting different.

I don't normally use RX2 squelch.
I only noticed it because I just made a pull request regarding picSquelch.

![sqrx2](https://github.com/ramdor/Thetis/assets/27503182/65083fdb-52fb-464f-a4a6-61cec00f0894)

**Comment by ramdor** [comment]
hah we must be in a simulation Sigi. I just fixed that when doing a code_clean pass through console.cs. Should be fixed in latest push to master, if not will re-open. Thanks.

**Comment by DH1KLM** [comment]
probably a glitch in the matrix. Hihi
