### ISSUE TITLE
TСI error when working CWU

### ISSUE THREAD

**Issue by RU6AI** [ramdor/Thetis#365]
I noticed a long time ago that the exchange via TCI in conjunction with the LOGHX hardware log when operating in the CWU mode is not correct.

When operating from 1.8 to 10 MHz, everything happens correctly. Log Tethis shows the correct exchange. And when operating at 14 MHz and higher, there is an error in the log and LOGHX does not switch Tethis to the correct CWU mode.
The problem, judging by the Tethis log, is not in the hardware log but in Tethi
![1DDDD1111](https://github.com/ramdor/Thetis/assets/152470699/22db3834-9152-4587-b52f-e99ac1a5a3a2)
![33DDD333](https://github.com/ramdor/Thetis/assets/152470699/f9cf69e7-4946-4ded-964a-c88d367e0863)
s

**Comment by ramdor** [comment]
LOGHX does not know about CWU or CWL that Thetis uses. There is an option which will always send CW instead of CWU or CWL to LOGHX.

![image](https://github.com/ramdor/Thetis/assets/3124967/39345533-b322-4d81-a9e3-d418f7b56b59)

Also, when a modulation type message comes in from LOGHX it is only CW, and Thetis defaults to CWL when it sees this irrespective of frequency. I could add an option to select CWU if 10MHz and above?

**Comment by RU6AI** [comment]
Good afternoon Thanks for the answer. I have this checkbox checked, but it does not solve the problem.
If possible, add the ability to select CWU after 10 MHz

**Comment by ramdor** [comment]
this feature has been added to 2.10.3.5 u2  and released as an update. You will see u2 in the titlebar. Please test and let me know how it goes. The new option is in the TCI tab.

**Comment by RU6AI** [comment]
Hi.Unfortunately it didn’t help... Up to 10 MHz everything is fine. And above, you can see from the screen that Tethis does not transmit CWU
![Uploading 33.jpg…]()
 from the log

**Comment by RU6AI** [comment]
![33](https://github.com/ramdor/Thetis/assets/152470699/da9c1dea-4afa-4a51-813f-97a002689c0d)

**Comment by RU6AI** [comment]
But this is not critical. You can leave it for later, when you have time. Or leave it like that.

**Comment by ramdor** [comment]
so I setup loghx, got some spots in for 10m etc, and tried it.  Seems fine, test here : https://youtu.be/gdeGd2m1hfU

I am not sure why LOGHX is sending ??? in the modulation message to Thetis. Perhaps LOGHX doesnt know what modulation to be in for the specific frequency you are on at the time?

You could try and reset your band plan in LOGHX

![image](https://github.com/ramdor/Thetis/assets/3124967/58d93c3e-89f8-42b1-a34c-7a0d79a70419)

**Comment by RU6AI** [comment]
Hi.I probably didn’t express myself very clearly... The problem is that when I, for example, change the frequency from 3.543 to 3.643, then in Tethys and LOGHX everything is displayed and switches normally. That is, when installing 3.543, CWL is installed in Tethis and CW in LOGSHH. And when installing 3.643, LSB is automatically installed in Tethis and SSB in LOGHX .
I do the same thing on 21.053 - there it immediately becomes USB, if you force the installation of CWU - and then go to 21.153 - it works correctly. That is, in Tethys the mode switches to USB and to LOGHX mode SSB. BUT....If you go to frequency 21053, it goes to LOGHX correctly, that is, the settings in it are correct. And Tethys remains in USB mode. I have the latest LOGHX version 742.         https://youtu.be/sasIlRRtAiM

**Comment by ramdor** [comment]
band stack entries are changing the mode, unless you have something set in loghx that is doing it. My system does not auto change mode depending on frequency, unless I have setup band stack entries to do that

**Comment by RU6AI** [comment]
Let's leave this question aside. I have already distracted you from an important and necessary matter for all radio amateurs. This is such a small thing that you shouldn’t pay attention to it. Perhaps this is really a problem on the LOGHX side. Moreover, other radio amateurs do not mention this. Thank you for supporting the wonderful Tethys program. Sorry for the interruption. 73!
