### ISSUE TITLE
Thetis V2.10.3.5 Release

### ISSUE THREAD

**Issue by Beefus** [ramdor/Thetis#370]
**Describe the bug**
Setup->Display->RX 1 the Spectrum Grid Min Val appears to no longer be band independent.
Installed V2.10.3.5 pre-release 3 and problem not present.

**To Reproduce**
On 10 meters set Min Val to -145
On 15 meters set Min Val to -135
Select 10 meters and note that Min Val is -135 instead of expected -145

Thanks for all the wonderful improvements, 
Jack, WB8BFS

**Comment by ramdor** [comment]
should be fixed now Jack, thanks for the report. Caused by my recent 'code clean'. Updated release for 2.10.3.5.  It will show 'u2' in the titlebar.
