### ISSUE TITLE
NO RX after a not repeatable time (20-100 minutes) of operation, when DIVERSITY is activated

### ISSUE THREAD

**Issue by dl5tt** [ramdor/Thetis#380]
Hi Richie,

I have a suspicious behavior of Thetis v2.10.3.5. u2, if I am using DIVERSITY, (allways ON).

After a a random period (e.g. 30 minutes up to 2 hours) of operation (most CW and sometimes RTTY oder PSK or WSJTX), 
the RX suddenly doesn't work, after a transmission in CW or FLDIGI or WSJTX. There is no audio output at the speakers nor an audio output on VAC1 or VAC2. I don't have experience with SSB, because I don't use it (or very rarely)
When I disable DIVERSITY in this case, RX1 comes back, but I if enable DIVERSITY again, the RX is not working. That means no spectrum no waterfall and so on.
It is also not working, when DIVERSITY is enabled but switched to RX1 or RX2.

Restarting of THETIS doesn't fix the problem.
To fix the problem, I have to switch off the ANAN 7000 MKII and to restart it.

By the way: 
I am using an external PC, Windows11 (up to date) , Protocol 2, no sequence errors. 
I am also using the MIDI-interface to control VFO, volumes and a lot of other functions. The DIVERSITY phase is also controlled by a jogwheel, what s very comfortable.

I didn't had this behavior with the previous versions.
I didn't install older versions to test ist, because I am not sure to loose parameters in the databasxe.XML-file.

Sometimes this problem occurs only after 1 or 2 hours. 

Thank you for your superb work the last years. I appreciate your knowledge and your time.

73 de Josef (DL5TT)

**Comment by ramdor** [comment]
hmm, power cycling the hardware as the only way to fix something is normally indicative of a firmware/timing issue and not something in Thetis. When RX cuts out randomly I assume there is no RX displayed in the spectral area?

**Comment by ramdor** [comment]
not able to replicate this, closing
