### ISSUE TITLE
ZZOA command

### ISSUE THREAD

**Issue by n4py** [ramdor/Thetis#385]
Please implement the ZZOA command so the receive antenna can be changed from external programs.

**Comment by ramdor** [comment]
ZZOA (rx) and ZZOC (tx) have been implemented.

examples
ZZOA;  will return  ZZOAx;  where X is rx antenna 1-3
ZZOC;  will return  ZZOCx;  where X is tx antenna 1-3
ZZOA2;  will select rx antenna 2 for the current RX1 band
