### ISSUE TITLE
Container 1 TRX1 bug

### ISSUE THREAD

**Issue by n4py** [ramdor/Thetis#389]
I'm using a multimeter container.  I have Vfo Display selected as the first meter.  It shows the frequency of VFO A and VFO B.  VFO A is always correct.  However VFO B frequency does not get any frequency if RX2 is turned on.

**Comment by ramdor** [comment]
Thetis does not have vfoB for RX1 when RX2 is enabled, so it it is greyed out in the TRX1 container. It does however have a sub vfo if subrx is used. To show vfoB when RX2 is enabled you need to use a TRX2 container.
