### ISSUE TITLE
Key Line Inhibit During Tune

### ISSUE THREAD

**Issue by kw4ex** [ramdor/Thetis#391]
Need for not keying amplifier while generation Tune signal

**Describe the solution you'd like**

Option for Thetis  - Do not toggle the “Key Line” when pressing the TUN option.   This would allow an external tuner to be used without keying an amplifier.

**Comment by ramdor** [comment]
wire the keyline through a relay that uses the OC pins, and configure the Transmit Pin Action accordingly

**Comment by laurencebarker** [comment]
This is a firmware issue, not a Thetis one.

 

 

 

Laurence Barker G8NJJ

***@***.***

 

From: kw4ex ***@***.***> 
Sent: Tuesday, January 16, 2024 8:20 PM
To: ramdor/Thetis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ramdor/Thetis] Key Line Inhibit During Tune (Issue #391)

 

Need for not keying amplifier while generation Tune signal

Describe the solution you'd like

Option for Thetis - Do not toggle the “Key Line” when pressing the TUN option. This would allow an external tuner to be used without keying an amplifier.

**Comment by RdWing** [comment]
> wire the keyline through a relay that uses the OC pins, and configure the Transmit Pin Action accordingly

The only problem with this, and this might be a firmware problem, but CW via QSK will fail to key the OC pin used for amp keying.
