### ISSUE TITLE
J16 pins working as Alex internal filter  [FEATURE]

### ISSUE THREAD

**Issue by Roturbo** [ramdor/Thetis#394]
I´m planing to add external filters controlled with BCD codes on J16 pins,
but i notice that control is not working on all frequencies as the Alex filters do. 

**Is your feature request related to a problem? Please describe.**
.
J16 pins are only working inside ham bands.  
.

**Describe the solution you'd like**
.
Empty band (1 or more) **_were we can chose other bands or frequency range_** in 
order to use the same BCD codes on J16 to activate external filters on RX and TX. 
.

**Describe alternatives you've considered**
Or just include 11m band with same filter BCD codes as 10m band
like is does on ALEX internal filters.
.

**Additional context**
![J16](https://github.com/ramdor/Thetis/assets/91867260/b451490a-ce65-4abf-9fc4-f2d4da28b5f4)

Regards

**Comment by DH1KLM** [comment]
I think it's right the way it is. For non-HAM bands there is the SWL tab.

**Comment by Roturbo** [comment]
Hello,

yes you are correct, i forget to check the SWL, i read VHF on the left and i have assume the other
one was UHF or something else without reading with attention.

Many tanks for your replay and help,, now i can plan one Arduino with with LCD 
and a BCD decoder also a manual rotating switch to select different filters relays.


Regards

**Comment by Roturbo** [comment]
Option already in software.


Closed
