### ISSUE TITLE
Thetis Won't Recognize Correctly Named ASIO Driver 

### ISSUE THREAD

**Issue by W2PH** [ramdor/Thetis#395]
I am using the Rodecaster Duo audio mixer/"daw" and Thetis gives me "Issue Starting CM ASIO....." and shows red instead of green.  I have run hostsample.exe and see the RODEcaster ASIO driver listed.  The regedit entry is coorect also.  If I look at the VAC1 potential drivers I do see ASIO with RODEcaster as the possible choices.  I have both VAC's turned off .  Any ideas why Thetis can't see the ASIO driver for RODEcaster?  

Ed W2PH

**Comment by W2PH** [comment]
Here is the aforementioned ASIO setup for RODEcaster.
[RODECasterASIO.zip](https://github.com/ramdor/Thetis/files/14001996/RODECasterASIO.zip)

**Comment by W4WMT** [comment]
Hi Ed,

Unfortunately, the "RODECaster Duo" podcast console's minimum buffer size is 96, which makes it incompatible with the Thetis ChannelMaster (which requires 64).

Maybe you could try a regular USB audio interface (e.g. Behringer UMC202HD) or better yet, a PCIe audio adapter for the very best performance.

73,
Bryan W4WMT

**Comment by w-u-2-o** [comment]
Since this is likely to be a common problem, perhaps it would be worth trapping that error and displaying an appropriate message, e.g. "Incompatible driver buffer size (xxx)" where xxx is the driver buffer size.

**Comment by W4WMT** [comment]
Yes, the next revision does exactly that.

Fortunately though, it doesn't appear to be a common problem.  AFAIK the RODE "RODECaster" is the only device that fails in this way.

**Comment by W2PH** [comment]
Bryan,
Thanks for identifying this problem.  It is unfortunate.  I do have a Behringer but the preamp is too noisey when used with my low output broadcast style dynamic mic, so I will have to stick with using VAC.
Thanks,
Ed W2PH

**Comment by W2PH** [comment]
Bryan et al,
I came up with a workaround.  I am using the RODEcaster DUO to provide all my audio processing then feeding its line out (zero latency) into my Behringer UMC404HD (using ASIO) (with the lousy preamps) at line level to get rid of the noise.  I then take the Behringer Line outs to feed my studio monitors.   All seems to work fine and my RODEcaster USB output is available for all my other audio needs (internet radio station and misc recording.)

I appreciate the quick response as I have little hair left to be pulled out 😊
73
Ed W2PH

**Comment by W4WMT** [comment]
Nice idea.  Just use the RODE-CASTER as a glorified mic pre  :-)  Problem solved!

I am curious about one other thing though.  When using the RODE-CASTER with VAC1, were you able to use the ASIO driver?  And if so, what buffer size did you have to select to get it to work?

73,
Bryan W4WMT

**Comment by W2PH** [comment]
Hi Bryan,
I will check later.  I did get it to work but audio levels seemed down quite a bit .  I don’t remember what buffer size.  It is normally set to 128 @ 48k and I didn’t change it when I tried asio on the vac 1 without the registry entry.  So far all seems to work well using the RODEcaster Duo as a super low noise preamp driving the Behringer at line level.

Cheers,
Ed

**Comment by W2PH** [comment]
Hi Bryan,
I finally gave up on using cmASIO.  Putting two preamps in tandem just to make use of the driver wasn’t worth the extra noise no matter how I tried to balance the gains.  The problem is that now I went back to normal audio by removing the asio driver info with regedit, restarting the 7000 and then Thetis and then setting my VAC1 to look at the usb output of the Rodecaster which works just fine(transmit audio), but now the external rx audio jack on the front panel appears to be dead so I have lost receive audio whether VAC1  is on or off.  I can’ see anything else I changed,  Any ideas?
Ed W2PH

**Comment by W2PH** [comment]
Bryan,
I duid a database reset then reloaded the latest dbf and all is back to normal.
Ed

**Comment by w-u-2-o** [comment]
Just a reminder: the Github issues feature is for bug reports and feature
requests. For day to day operational problems please use the Apache Forum:
https://community.apache-labs.com/

**Comment by ramdor** [comment]
closing, as this is more support/problem related as @w-u-2-o mentions above. Please re-open if not the case.
