### ISSUE TITLE
Link "xPA" and "Rx Bypass on Tx" for better PureSignal feedback.

### ISSUE THREAD

**Issue by rfengrs** [ramdor/Thetis#396]
When running PureSignal from an external monitoring point with additional attenuation (50+ dB for an external power amplifier) without the xPA Engaged, the pure signal feedback is too low and becomes unstable without "unclicking" "Rx Bypass on Tx".

It would be nice to link the "xPA" option, and "Rx Bypass on Tx" to a NOT condition for normal feedback monitoring of the transmitter driver without an external power amplifier engaged..

It would be nice to provide a setup option to switch feedback sources from Internal to External when "xPA" is engaged.

**Describe alternatives you've considered**
The only alternative may be to design a hardware solution to my external power amplifier.

**Additional context**
I am part of the 80M 3630 group. We have a lot of hardware, SSPA, and Anan / Thetis experience. 
 Thank you. Michael Martin - W9AAM

**Comment by RdWing** [comment]
xPA has nothing to do with PureSignal. xPA is a software selectable button to control open collector outputs.
If your external sampler has a coupling factor of 50 dB, that should still be appropriate for barefoot operation without issue.

Please verify if your sampler is returning -50dBc or not when in barefoot mode.

**Comment by rfengrs** [comment]
The External Sampler is >-55dB and is within the amplifier and inline when
the amplifier is being keyed and provides "15" in the ATT box being keyed
by "xPA".
When running Barefoot the ATT Box is at "0" and Pure Signal  is short
Feedback.
it is necessary to go back to internal feedback in the 7000 for Pure Signal
to be effective barefoot.
I can continue to deal with it and perhaps remove some of the external pad
and see if I can get enough to make Pure Signal happy. I just don't want to
smoke the radio pads.
I built the amplifier so I can come up with something...

Thank you for the great software for our Anan Radios.
Michael - W9AAM

**Comment by RdWing** [comment]
Michael,
It sounds like the external sampler is not being engaged when in barefoot mode. A -55 dBc sampler should work without issue at 100W power level.

**Comment by rfengrs** [comment]
I run about 20W Drive barefoot, thus part of the rub....

M

**Comment by RdWing** [comment]
20w barefoot works fine here with an external -55 dB sampler, with a auto puresignal value of 4. Again, it sounds like your external sampler is returning 0 signal when your amp is in standby.

**Comment by rfengrs** [comment]
I will review my schematic again, and remove some of the additional fixed
pad.
M

**Comment by RdWing** [comment]
Here's a S21 sweep of the sampler here. This level should work fine 
![Picture1](https://github.com/ramdor/Thetis/assets/19214916/2f38ac34-d5bb-45ad-84c3-ec27a3a1cc13)

**Comment by rfengrs** [comment]
I will take out some of the additional amplifier pad and let the ATT Pad
deal with it.
Thank you for a great SW Package.

Michael - W9AAM

**Comment by ramdor** [comment]
thanks for the support on this issue @RdWing . I will close this.

**Comment by rfengrs** [comment]
Richie:
I have since relocated my Internal Brune Bridge Coupler from the Amplifier
Pallet Output to the Antenna Side of the Antenna Relay to be able to sample
both barefoot and amplified output.
The Auto ATT is dealing with things fine now.
Running  2.10.3.6 dev_3 as we speak.

Thank you for the great SW.
Michael - W9AAM
