### ISSUE TITLE
CWX Keyboard

### ISSUE THREAD

**Issue by eriwanradio** [ramdor/Thetis#400]
When opening CWX I can use the keyboard of the pc to send cw. After closing CWX and re-opening later the keyboard does not send cw even if it is correct activated in the CWX-menu.
This needs to restart Thetis to get the keyboard sending cw again. 

Using Anan 7000dle MKII EP4CGX150F896 Cyclone IV series FPGA with Firmware Metis_Orion_MkII_Protocol_2_v2.2.2 and
Thetis Thetis-v2.10.3.6-dev_2.x64

**Comment by ramdor** [comment]
this is resolved locally, but currently working on #399, which hopefully will find time to finish in a week or two.
