### ISSUE TITLE
[BUG] CW split operations. Sidetone only with subrx on.

### ISSUE THREAD

**Issue by IU4JNR** [ramdor/Thetis#406]
FW 2.2.2 on ANAN7000 DLEMK2;
Database created from scratch;

I found that in CW/split the TX monitor is audible only when the subrx is on. In SSB though there is a slight echo, TX monitor works when in split without the need of enabling SubRX.

**To Reproduce**
1. Select cw
2. Select Qsplit
3. Disable subrx
4. Sidetone is not reproduced

**Desktop (please complete the following information):**
 - OS: Windows11

**Additional context**
Headphones connected to the front plug

**Comment by W2PA** [comment]
I can not reproduce this.  In the main console, is the sidetone box checked?  Are you operating in SEMI or QSK break-in?

With the sidetone box checked you should always hear a sidetone when keying in CW, no matter which break-in mode is selected.

If in QSK mode you will hear both the sidetone and your transmitted tone.  If you un-check sidetone in QSK you will only hear your transmitted tone in the main receiver (unless RIT or XIT is on and causing rx and tx frequencies to be different).  

If in QSK mode *and* split, you will hear the sidetone if the sidetone box is checked, plus you will hear your transmitted tone from the subreceiver only if the subreceiver is active.

73, Chris, W2PA

**Comment by IU4JNR** [comment]
Chris thanks for reply.
I didn't mention the bk-in since I can only work semi with my pa.
The issue is when I use split and I turn the subrx off ( or even lower the subrx volume).
This issue is only in CW and with any combination of sidetone and monitor.
This issue arose after prot2/fw 2.2.2 installation.
Max
Iu4jnr

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
