### ISSUE TITLE
After the the forced update Thetis will not start (fatal error "Index was outside the bounds of the array. ..."  [BUG]

### ISSUE THREAD

**Issue by neil969** [ramdor/Thetis#412]
**Describe the bug**
Attempting to start Thetis after doing the forced update  A "fatal error" is encountered

**To Reproduce**
Steps to reproduce the behaviour:
1. download the  new beta from here
2. download the most recent Thetis release from the other repository
3. install the official release over the old one 
4. unzip the "HL2 Beta" into a different directory
5. Run the Official Thetis to ensure it runs OK & Close
6. run the thetis.exe from the "Thetis_x64_2_10_3_5-HL2-beta1" folder
7. See the error in the middle of teh screen :( 

**Expected behaviour**
Thetis should run like it did before 

**Screenshots**
See screenshot 
![image](https://github.com/ramdor/Thetis/assets/22851918/185499ac-c2c8-43d6-b415-ddbdbc1239ef)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10

**Additional context**
All was working fine until the old beta timed out ..

**Comment by DH1KLM** [comment]
Start your Thetis with Ctrl key pressed to do a database update.

**Comment by neil969** [comment]
Perfect!! That worked, thank you.. A function there that I didn't know about :) 

Hopefully anyone with the same issue will find this -
Thanks
