### ISSUE TITLE
[BUG] When PS is enabled, BPF's are bypassed on transmit

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#413]
Is this the intended behavior? When sending any transmission with PS engaged, the BPF are switched out as if the "BPF Bypass on TX" box was checked, even if it isn't checked.

V. 2.10.3.6 d2

**Comment by ramdor** [comment]
this has been in place since at least 2.9.0. An orionII or saturn based radio bypasses BPFs on tx when PS is enabled, even if the option is unchecked.

![image](https://github.com/ramdor/Thetis/assets/3124967/266eea96-0ac5-4e95-847a-3c8eaf393c82)
