### ISSUE TITLE
[BUG] Audio stuttering when RX control adjusted

### ISSUE THREAD

**Issue by SDRDesk** [ramdor/Thetis#416]
Regarding wave.cs  :

 // private object m_inversGainlock = new object();  Please, no locks on the audio path, ever,
    // unless you want TX and RX to stutter every time you adjust the RX gain control!

// Use volatile for the values updated instead.

    private volatile bool m_bMox = false;
    private volatile float m_fInverseGain = 1f;

HTH

**Comment by ramdor** [comment]
many thanks, i have changed as you suggest. Fantastic.
