### ISSUE TITLE
[BUG] If MIC slider is higher than 40dB, crash report!

### ISSUE THREAD

**Issue by ON7OFF** [ramdor/Thetis#417]
I'm using the HL2 with the companion board. 
If I increase the microphone input on the front panel and go beyond 40dB (note that the slider allow to go up to 70dB, and after you save your transmit profile, I get a fatal error when starting Thetis. 
![image](https://github.com/ramdor/Thetis/assets/153032115/ec652438-7f5e-4b76-b25c-77317d168b4f)

![image](https://github.com/ramdor/Thetis/assets/153032115/add422e9-23a7-4bb8-8486-bb2bf4aa7717)

I assume there is a database check on the allowed values, and I think it is allowed to set the value up to 40dB and you can't go beyond. 

Hope you can reproduce the issue. 

73 de ON7OFF

**Comment by w-u-2-o** [comment]
The work-around for this is to go to Settings > Transmit and change max.
mic gain to 39.

I don't know anyone that is using > 40dB of mic gain, but I suppose
stranger things have happened.

Most people run with mic gain somewhere between 10 and -40. Indeed, those
are very nice settings for max. and min. and make for good resolution on
the mic gain slider control.

73,

Scott
