### ISSUE TITLE
[FEATURE]6m S Units definition (option)

### ISSUE THREAD

**Issue by VK6CPU** [ramdor/Thetis#418]
Enhancement suggestion.

Option to use HF convention for calculation of S units above 30 MHz and including 50Mhz band. 
This is a convention used by most Manufacturers and operators.

"Today two reference values exist: for frequencies below 30 MHz, S9 is defined as a voltage of 50 μV over 50 Ω at the receiver antenna connector; for frequencies above 30 MHz, S9 is defined as a voltage of 5 μV over 50 Ω at the receiver antenna connector. "

**Comment by mdblack98** [comment]
For a reference on that....

http://www.algonet.se/~k-jarl/ssa/IARU/smeter.html

Mike W9MDB








On Sunday, April 14, 2024 at 09:38:51 PM CDT, VK6CPU ***@***.***> wrote: 







Enhancement suggestion.

Option to use HF convention for calculation of S units above 30 MHz and including 50Mhz band.
This is a convention used by most Manufacturers and operators.

"Today two reference values exist: for frequencies below 30 MHz, S9 is defined as a voltage of 50 μV over 50 Ω at the receiver antenna connector; for frequencies above 30 MHz, S9 is defined as a voltage of 5 μV over 50 Ω at the receiver antenna connector. "

**Comment by ramdor** [comment]
@VK6CPU have you tested this? Because it is already coded for. 30MHz and above is using the -93dBm level for S9.

For example, a signal rx'ed on 50.075MHz gave the following with the legacy meters

S meter : S9 +20
dBm : -73.7 dBm
uV : 46.36 uV

**Comment by w-u-2-o** [comment]
The S-meter standard reference levels are defined by IARU Region 1 Technical Recommendation R.1, as ratified at both the Brighton 1981 and Torrelmolinos 1990 meetings. This standardization is documented in that recommendation as follows:

STANDARDISATION OF S-METER READINGS
1. One S-unit corresponds to a signal level difference of 6 dB,
2. On the bands below 30 MHz a meter deviation of S-9 corresponds to an available power of -73 dBm from a continuous wave signal generator connected to the receiver input terminals,
3. On the bands above 144 MHz this available power shall be -93 dBm,
4. The metering system shall be based on quasi-peak detection with an attack time of 10 msec ± 2 msec and a decay time constant of at least 500 msec.

**_Unfortunately, this leaves S-meter reference levels undefined for the 6M band._** For 6M, Thetis currently uses the "VHF" reference level of S9 = -93dBm. Whether this is correct or not is hard to say given that the IARU never defined it.

73,

Scott

**Comment by mdblack98** [comment]
Seem that was updated....Jan 1994....

https://hamwaves.com/decibel/doc/iaru.region.1.s-meter.pdf

Mike W9MDB








On Monday, April 15, 2024 at 07:33:57 AM CDT, w-u-2-o ***@***.***> wrote: 







The S-meter standard reference levels are defined by IARU Region 1 Technical Recommendation R.1, as ratified at both the Brighton 1981 and Torrelmolinos 1990 meetings. This standardization is documented in that recommendation as follows:

STANDARDISATION OF S-METER READINGS

    1. One S-unit corresponds to a signal level difference of 6 dB,
    2. On the bands below 30 MHz a meter deviation of S-9 corresponds to an available power of -73 dBm from a continuous wave signal generator connected to the receiver input terminals,
    3. On the bands above 144 MHz this available power shall be -93 dBm,
    4. The metering system shall be based on quasi-peak detection with an attack time of 10 msec ± 2 msec and a decay time constant of at least 500 msec.

Unfortunately, this leaves S-meter reference levels undefined for the 6M band. For 6M, Thetis currently uses the "VHF" reference level of S9 = -93dBm. Whether this is correct or not is hard to say given that the IARU never defined it.

73,

Scott

**Comment by VK6CPU** [comment]
@ramdor  - yes.  Above 29.999999 Mhz the transform flips from the -73 to the -93 dbm reference.

As an enhancement, on my part its fairly low priority. 

As Scott says 6m (and 8m) dont appear to be covered by the IARU definition - but the HF definition seems to be the one adopted/implemented by most rig manufacturers. Having checked with several other Ops Flex, Yaesu, Icom all use the IARU HF defintion for 6m.

**Comment by mdblack98** [comment]
And another reason you can't compare S Meter values with anybody else.  Perhaps except for SDRs that are calibrated well.

Mike W9MDB








On Monday, April 15, 2024 at 09:08:47 PM CDT, VK6CPU ***@***.***> wrote: 







@ramdor - yes. Above 29.999999 Mhz the transform flips from the -73 to the -93 dbm reference.

As an enhancement, on my part its fairly low priority.

As Scott says 6m (and 8m) dont appear to be covered by the IARU definition - but the HF definition seems to be the one adopted/implemented by most rig manufacturers. Having checked with several other Ops Flex, Yaesu, Icom all use the IARU HF defintion for 6m.

**Comment by ramdor** [comment]
added feature

![image](https://github.com/ramdor/Thetis/assets/3124967/6a4cbd58-9b34-4c7f-9aa0-105bb6d7cdb8)
