### ISSUE TITLE
Add XVTR Antenna to XVTR setting

### ISSUE THREAD

**Issue by n4py** [ramdor/Thetis#424]
Currently for the Anan 8000 and maybe all other radios, the transverter settings have no way to set the receive antenna.  I want to use ant 3 for my transverter receive connection.  My transverter uses separate receive and transmit connections.  In order for me to use ant 3, I have to change the 10 meter receive antenna to be ant 3.  While this works, it is a nuisance and I have to remember to change the 10 meter antenna back to ant 1 after using the transverter.

A new column in the XVTR setup would solve this by adding a receive antenna column to the setup window.

**Comment by ramdor** [comment]
implemented : https://youtu.be/FYhDYbqnx3c

**Comment by ramdor** [comment]
waiting for a merge. Will close this.
