### ISSUE TITLE
Using other than CAT1 to control HobbyPCB Amps Band Switching

### ISSUE THREAD

**Issue by devmrs** [ramdor/Thetis#430]
I have a HobbyPCB Hardrock-500. It works fine with Cat control **AS LONG AS IT IS IN CAT1 control.** The Cat option "Kenwood AI" must be checked. I also have a Hardrock-50 amp that uses the same cat control as the Hardrock-500. I put the HR50 in Cat4. No go. The HR50 only switches bands when in Cat1 Control. I'm using the HR50 as a bandpass filter for my Hermes SDR. I would like to control both amps but the only amp I can control is the one in CAT1 -- nowhere else. Is this because the Kenwood AI checkbox only affects CAT1?

As a workaround, I purchased Fabulatech.com Serial Port Splitter to allow Cat 1 Control to control two devices.
![image](https://github.com/ramdor/Thetis/assets/39437673/7a3f810c-9283-41b2-940f-3b835271ad82)

**Comment by ramdor** [comment]
will be available in dev_4 at some point

![image](https://github.com/ramdor/Thetis/assets/3124967/b402dd85-544d-470d-b7e7-ebee2e3c79ba)
