### ISSUE TITLE
Memory Interface Thetis X64,[BUG]

### ISSUE THREAD

**Issue by pa0alw** [ramdor/Thetis#457]
Problem  to make a audio record with the "Memory Interface"

When i try to make a recording via the "Memory Interface" button it will fail.First when try to open the "Open Rec Folder" nothing happend.
I find out that the folder is "User\......\Music\Thetis "folder,
When i start a recording it will display in the directory "User\...\Music\Thetis " folder but when the recording is fineshed, the recording file disappear immediately from the recording directory.
So is this a bug or do i something wrong?
Using Thetis V2.10.3.6 x64 dev_4
Anan10 with Firmware 3.1
Protocol 1

OS Windows 10, 8 Mb memory

73, Walter
PA0ALW

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Memory'
2. Click on 'Open Record Folder'
3. "Nothing happends"

**Comment by ramdor** [comment]
the code was commented out about a year ago, so there is nothing behind that 'open record folder'. I've not had a chance to test the scheduled recording as yet, but for it to disappear, it must either be Thetis moving it, or some virus checker/music app? I will update when I have more info.

**Comment by ramdor** [comment]
ok, I looked into this, and all code was commented about a year ago, during Doug's related work on sorting out the directory/path code in Thetis. It looks like the audio is recorded as expected, but the code to move it somewhere has been commented out in function TOMP3(). The file is then deleted. There are obviously very few users who use this feature as it has not been raised as a problem for over a year.

**Comment by ramdor** [comment]
![image](https://github.com/user-attachments/assets/e51086c0-15cb-43a2-b76d-21e08ee3e681)

**Comment by pa0alw** [comment]
Thanks for the info Richie.
Looks i was one of the few.
73,Walter.

**Comment by ramdor** [comment]
I commented the delete, and patched the code back in for the open recording folder Walter. It did seem to record a wav file so that bit is now working. I guess 5 years ago, the MP3 converter got removed from the project and all of this was commented out.

It will be back for dev_7 at the end of the week.

**Comment by pa0alw** [comment]
Richie,

Thanks for the fb work.

73,Walter

**Comment by ramdor** [comment]
part of the #462 push
