### ISSUE TITLE
[BUG] path illustrator broken, no connections are shown

### ISSUE THREAD

**Issue by grabauter** [ramdor/Thetis#458]
**Describe the bug**
No connections visible in Path Illustrator.

**To Reproduce**
Click on PI in the top bar menu.

**Expected behaviour**
Lines shall be visible. This was the case earlier, unfortunately I don't know the behaviour changed. Wanted to use the PI now because I received my Anan-G2.

**Screenshots**

![image](https://github.com/user-attachments/assets/b22ca902-0cb6-4e15-8396-66e5bee97b09)

**Desktop (please complete the following information):**
Windows 11

**Additional context**
I changed skins, but the problem persists.

Version: v2.10.3.6x64 dev_6b

**Comment by ramdor** [comment]
yes i know, and i wont be fixing it. It was raised as non operational years ago, but I have less than zero interest in doing anything about it. Someone else can though, nothing stopping them.

**Comment by ramdor** [comment]
closing this as it is already listed in the wish list #55. 7000/8000/G2's are not currently supported in PI.
