### ISSUE TITLE
Transmission of audio stream via TCI

### ISSUE THREAD

**Issue by RU6AI** [ramdor/Thetis#459]
I really want the audio stream to be transmitted through the TCI, and not through VAC.

When launching an external program (for example JTDX), which allows data and audio stream exchange via TCI, I wanted to avoid using the external VAC program and transmit the audio stream directly

Approximately like the ExpertSDR3 program

So that when choosing TCI, the sound also goes according to TCI

**Comment by ramdor** [comment]
please use search ;)   #6

**Comment by RU6AI** [comment]
Sorry
