### ISSUE TITLE
Closing Thetis by a MIDI button results in message pane "please wait..." [BUG]

### ISSUE THREAD

**Issue by PD3LKG** [ramdor/Thetis#460]
**Describe the bug**

I had the midi Command "Close Thetis" by mistake assigned to a button. (instead of the Power button)
I tried the Close command anyway: it closes the Thetis window but a "Please Wait" pane appears and will not go away.
Had to close Thetis by Program Manager.

I suspect that nobody uses this command, maybe remove it from the command list? 

OS: WIN11, Thetis 2.10.3.5, 7000DLE MkII black, FW 2.1.1.18, prot 2

**Comment by ramdor** [comment]
fixed. Will be included in next release. Thanks for reporting it.

**Comment by PD3LKG** [comment]
Many thanks for all your work!
