### ISSUE TITLE
Levels in DUP display mode incorrect [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#47]
**Describe the bug**

When transmitting, signal amplitude levels shown on the panadapter in DUP mode are incorrect.

**To Reproduce**

Consider the following example:

- Two-tone waveform at 1600W total RF power out. 1600W = 62dBm.
- Each individual tone is 6dB below that total RF power level, or 56dBm.
- Coupling factor is 50dB, so rear panel input level for each tone is +6dBm.
- PureSignal drives the attenuator to 19dB, this is exactly as expected for the PS algorithm at that feedback power level.
- Under these conditions the DUP display shows each tone at -20dBm.

**Expected behaviour**

DUP display should show +6dBm. On receive everything is referenced to the input level at the rear panel connector. During transmit this does not appear to be the case, but it ought to be.

**Desktop (please complete the following information):**

Win 10 Pro, Thetis 2.9.0.6, firmware 2.1.18, ANAN-8000DLE, PureSignal ON.

**Comment by ramdor** [comment]
Do you know what the internal coupling factor is inside a 7000dle MKII?  I got the following which seems to imply that it is around 50dB.

**Single Carrier**
25w 43.979dBm
sample result = -5.7dBm on the anan DUP screen
-49.6dB coupling attenuation in the anan

**Two Tone**
25w 43.979dBm each tone will be 6dB down = 37.979dBm per tone
sampled result = -11.6 dBm on the anan DUP screen
-49.6dB coupling attenuation in the anan

Ideally I need to inject known signal level into external sample port on this radio and check what is shown when tx'ing with DUP on.

**Comment by ramdor** [comment]
Did you have any updates to this Scott? or should we close it off for now?

**Comment by w-u-2-o** [comment]
Let me get to work on this right now. More to follow shortly.

**Comment by w-u-2-o** [comment]
Measurements completed. Confirmed there is a problem. Preparing a proper report.

**Comment by ramdor** [comment]
I guess various fft windows, fft sizes, detectors used, will give different results?

**Comment by ramdor** [comment]
![image](https://github.com/ramdor/Thetis/assets/3124967/44494d83-ca6a-4263-a739-99e47b2fa873)

can this be used to tweak it to where it should be?

**Comment by w-u-2-o** [comment]
Perhaps, but the level is off by 24dB, which is a lot!

**Comment by laurencebarker** [comment]
OK I’ve tracked through which ADC readings go where in Orion. This isn’t documented in the protocol2 spec.

 

Supply_volts  (as measured on Orion or Saturn) goes to bytes 49, 50; so I did have it right.

 

PA volts go to bytes 57, 58  (user_analog1)

PA current goes to bytes 55, 56 (user_analog2)

 

But with those corrections, no display.

 

 

 

 

Laurence Barker G8NJJ

***@***.***

**Comment by ramdor** [comment]
now reported in #137

**Comment by ramdor** [comment]
closed as duplicated
