### ISSUE TITLE
Step attenuator set to 31dB after TX cycle [BUG]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis#48]
**Describe the bug**

Under certain conditions, including in this example split op's with the VFO-A RX frequency out of band limits, at the cessation of a TX cycle (PTT deasserted) the S-ATT is set to 31dB.

**To Reproduce**

- Set mode to USB or LSB.
- Activate split.
- Set VFO-A to RX and place the frequency outside of an amateur band (US limit example 7457KHz).
- Set VFO-B to TX and place frequency inside of an amateur band (US limit example 7220KHz).
- Make a transmission. Method does not matter: MOX, PTT and VOX all produce the same results.
- Observe S-ATT change to 31dB from its previous setting.
- Reset S-ATT to desired level.
- Transmit again and observe it change again.

**Expected behaviour**

After a TX cycle the S-ATT should return to the value set by the operator prior to the TX cycle.

**Desktop (please complete the following information):**

Win 10 Pro, Thetis 2.9.0.6, firmware 2.1.18, ANAN-8000.

**Additional context**

There have been reports of improper S-ATT settings after TX cycles under other conditions.

**Comment by ramdor** [comment]
cant replicate this in 2.9.0.7 : https://youtu.be/rJpl4FufyjM

**Comment by ramdor** [comment]
investigate : open up band stack manager, and check which band Thetis thinks you are in when you move outside the amateur band, also check if the 'extended' option does anything (note this will probably kill your band stacks)

**Comment by w-u-2-o** [comment]
Extended option not selected.

I just replicated this again with VFO A set to 4.0295MHz and VFO B set to 3.6295MHz. Somewhat bizarrely, band stack reports "90M" under these conditions!

Perhaps it is fixed in 2.9.0.7?

**Comment by ramdor** [comment]
@w-u-2-o I have now replicated it. Will look into it shortly.
