### ISSUE TITLE
In 8B the autoagc function no longer works correctly.  It settles way above the noise floor.  I suspect it is related to the attenuator issues being addressed   all on Windows 10  Ed W2PH[BUG]

### ISSUE THREAD

**Issue by W2PH** [ramdor/Thetis#483]
**Describe the bug**
A clear and concise description of what the bug is. Include pertinent version numbers, such as Thetis vesion from title bar, firmware version, OS version etc.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by ramdor** [comment]
working as expected here : https://youtu.be/3Sz-QitGtvY

**Comment by ramdor** [comment]
closing this, as I don't believe it to be an issue. There have been no other reports, and it works as expected.
