### ISSUE TITLE
[BUG]at 160 meter there is no spectrum anymore

### ISSUE THREAD

**Issue by ThermoNuclear65** [ramdor/Thetis#486]
Hello ,at 160 meter there is no spectrum anymore , only waterfall.All the others bands are working properly .Kind Regards 73 Patrick

**Comment by w-u-2-o** [comment]
Why do you think this is a bug rather than user error?

**Comment by NC3Z** [comment]
A screenshot would be oh so helpful, oh wait, that is one of the items requested.

**Comment by ramdor** [comment]
Ensure that the spectrum grid displays a range where you expect your signal/noise floor to appear (green values). Additionally, verify that the min/max band is set to 160m (orange value). Alternatively, you can switch to a band that is functioning correctly and press the [=] button (in orange) to apply that band setting to all other bands.

![image](https://github.com/user-attachments/assets/a151493e-41ac-40b2-abe2-630c3f6dc69a)

**Comment by ramdor** [comment]
https://github.com/user-attachments/assets/8183b2b5-8657-4636-80c4-27688176f95e

**Comment by ThermoNuclear65** [comment]
Thanks RAMDOR , works now , need to get new glasses , the minimum and maximum of  the spectrum were both set at -119. Furthermore , just love the work and time you are putting into this . Please keep going. Kind Regards ,73 , Patrick.

**Comment by ramdor** [comment]
@ThermoNuclear65 no problem man, glad you got it sorted. Will close this off. We are starting a discord community where things like this could be covered quickly or with a shared screen. I will be making a video about it sometime in the week. Cheers.
