### ISSUE TITLE
[BUG] In Setup, Keyboard, no definition for PageDown

### ISSUE THREAD

**Issue by trancen** [ramdor/Thetis#508]
**Describe the bug**
defining keyboard hot keys for TUNE, there is NO "PageDown"

**To Reproduce**
Steps to reproduce the behaviour:
1. Settings
2. Keyboard
3. Under TUNE, BAND, RIT... 
4. Drop down list has PAGEUP, but no PAGEDOWN

**Expected behaviour**
Expecting a PageDown option

**Screenshots**
attached
![2024-09-09 10_39_54-Window](https://github.com/user-attachments/assets/f0d7cf34-d862-4947-a0d8-b21586761d07)

**Comment by ramdor** [comment]
PageDown is known as **Next** in the list. It is directly below PageUp.
