### ISSUE TITLE
Add option to power off when entering the database manager

### ISSUE THREAD

**Issue by w3ub** [ramdor/Thetis#509]
Been using the collapsed view a lot lately, for the much larger panadapter. I only have the bottom band buttons shown, along with a VFO container, and some meter containers.

When trying to use the database manager you get the pop-up that the radio is running and needs to be shut down ... but unless I expand the display, or add some of the display controls I can't access the power button. (I auto power on).

How about instead of just an error message saying the database manager can't continue until it is shut down, instead have a box to click to shut it down then and proceed into the database manager?

Doug

**Comment by ramdor** [comment]
Release Candidate 3 will include option to hold SHIFT when pressing ok to try to power down the radio. Of course you will then need to restart Thetis if you want to power it up if the power button is unavailable.

**Comment by w3ub** [comment]
Thanks!
