### ISSUE TITLE
Andromeda with 7000DLE MKII

### ISSUE THREAD

**Issue by k1sre** [ramdor/Thetis#510]
When loading SDR software for Andromeda, the Discord loads first and the power up of the 7000 dle MKll error message says no power

**Comment by ramdor** [comment]
no idea what this means, sorry

**Comment by k1sre** [comment]
Richie I sent the message . I downloaded the link for discord app linked to my andromeda/anan 7000 DLE MK ll When I reconnected and started the Andromeda The power button was blank and would not work and gave a message on to Check power connections I also tried changing to a different xlml for and removed the discord app to no avail.Help!  Mark Reinen ***@***.***’m ok on QRZSent from my iPhoneOn Sep 15, 2024, at 15:39, Richie ***@***.***> wrote:﻿
no idea what this means, sorry

**Comment by w-u-2-o** [comment]
Mark, it's not at all clear what your problem is. Discord has nothing to do
with Thetis. Are you trying to say you installed Discord on the PC built
into the Andromeda?

Also, GitHub issues are for discussing bugs and software development, not
for solving day to day problems. You might try posting on the Apache
community forum.

**Comment by ramdor** [comment]
@k1sre , thank you for updating the info. I assume by mentioning discord you mean that you obtained a new Thetis download from the discord server as I see you are registered there, like 100's of others. I also assume from your message you get the following error :

![image](https://github.com/user-attachments/assets/7f57893d-bcb7-4cd0-9baf-68badbade158)

There are many reasons why this could be. If you have been running a version of Thetis successfully previously, then I would do the following :

- use 'add removed programs' in windows to un-install any versions of Thetis that show up when you search for Thetis (do not worry, your database/config will not be removed). If there is more than one install, remove them all to avoid confusion
- reboot
- download a new install of Thetis, the one from here is the latest at the moment, and install : https://github.com/ramdor/Thetis/releases/tag/v2.10.3.6-rc3
- if you are still having issues, ensure that all the IP settings are correct in Thetis->Setup->General->H/W Select
- if that still fails, open a windows command prompt and use 'ping' to check that your radio is reachable. If you do not know how to use ping, do a google or youtube search
- you may have been using a command line argument -datapath: on your old install, this will not be kept on a new install. If so change the new Thetis shortcut appropriately

Also, as you are already on the Discord server, post there and ask for help. Myself or one of the hundreds of active users may offer to help  out and guide you through sharing your computer screen using Discord and/or where you can talk in real time to someone over voice audio to diagnose the problem.

Richie.

**Comment by ramdor** [comment]
and, if indeed you have installed Discord on the PC which is now preventing Thetis/Andromeda from running, then that is cause for concern, especially if you have uninstalled it. Over on the AL forums there will be guides to get you up and running again I am sure, and people that have experience of Andromeda setups.

**Comment by k1sre** [comment]
Thanks Richie.  I fixed the issue tonight and have the Andromeda up and running Yours Mark Reinen K1SRE Mid Coast MaineSent from my iPhoneOn Sep 15, 2024, at 20:52, Richie ***@***.***> wrote:﻿
and, if indeed you have installed Discord on the PC which is now preventing Thetis/Andromeda from running, then that is cause for concern, especially if you have uninstalled it. Over on the AL forums there will be guides to get you up and running again I am sure, and people that have experience of Andromeda setups.

**Comment by ramdor** [comment]
nice one Mark. Brilliant. Closing this. Cheers, 73.
