### ISSUE TITLE
[BUG] several thetis versions

### ISSUE THREAD

**Issue by ve7dqc** [ramdor/Thetis#512]
**Describe the bug**
XIT not able to enable between frequency 5.250 and 6.999MHZ.  This has been apparent on my system for a very long time (many versions of Thetis). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Frequency between 5.250 and 6.999 MHZ any mode or bandwidth.
2.  XIT will be disabled (greyed out)
3. change frequency to 5.249 or 7.000 MHZ
4. XIT will be enabled. (highlighted)

**Expected behaviour**
I would expect XIT to be able to enable at any frequency and work same as RIT.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows7/8.1/10/11/etc]

**Additional context**

**Comment by ramdor** [comment]
XIT gets turned off when band is 60m for some reason. I guess somewhere along the line someone decided that we are not allowed to xit on the 60m band.  Also, when running the radio in extended mode, then the 60m is classed from 5.25 to 7.0 mhz.

**Comment by ve7dqc** [comment]
I respectfully disagree with "feature" reasoning. To have XIT disabled for such a wide range (5.25-7.0mhz) when the 60m band is channized and extremely limited seems over kill to me. Since I use this area for other legal uses and with "extended" menu use I would assume that the software can be modified to still agree with the "feature" and have only the particular 60m channels have XIT disabled. Other added notes is that visually the Thetis software considers the 60m band between 5.250-5.499mhz.  At 5.500mhz the software switches to 49m band. There appears to be some inconsistencies here which while very minor should at some point have some attention allocated to. This is a great piece of software which I enjoy using and respect the amount of time and effort our authors but in it for the betterment of all users.  Please don't take this as bashing the software contributors or designers as I have great respect for their contributions.
