### ISSUE TITLE
[FEATURE] A-ATT - Automatic attenuation to prevent ADC overload.

### ISSUE THREAD

**Issue by Roturbo** [ramdor/Thetis#517]
**Is your feature request related to a problem? Please describe.**

Since my station is near a highway sometimes people are passing and i get
ADC overload because they use amplifiers on trucks etc, and i don´t need
to be on the same freq, other times i see the same with stations that are near.

If i have time i change the ATT to -30,, but if i have a second antenna on RX2 
i also get overload on the other ADC. 

**Describe the solution you'd like**

Hermes Lite 2 have now the A-ATT (Automatic Attenuation) were it regulates 
the input attenuation to avoid the same type of overload.

My idea is not to have a constant up and down because the Anan´s are much more stable,
the point is only if a signal goes over 9+30 it starts to increase attenuation on the 2 ADC´s.

This value may be optional, for example start attenuation only if hits 50dBm, 
also a delay or holding time to make it more smooth with SSB signals, once the
strong signal goes or the overload is not detected it goes to 0 attenuation. 

**Additional context**

This automatic attenuation may prevent damage of the ADC´s, because the overload may occur
on any point of the spectrum, and if we have the zoom to a different point than we only
see it if we are looking at the monitor, and sometimes we are not near the radio to see it
or to have time to change attenuation.

Just remember now, one thing is the signal inside the filter were we have a constant reading,
the other is a signal inside the spectrum but out of our filter= tuned freq, maybe in this case
it will need 2 triggers, one based on tuned freq using reading values, and the other based
on overload detection, or other reading off the full spectrum.  

Regards

**Comment by ramdor** [comment]
Something similar is now implemented in 2.10.3.7 test version, and the changes have hit the master branch. No full release of .7 has been made yet, only testing versions via the Discord testing group.

There is also a tx attenuator, and adc0 and adc1 attenuator, with 'unwind' time which can be used if required.

Closing.
