### ISSUE TITLE
[BUG]version 2.10.3.6 at startup

### ISSUE THREAD

**Issue by iowahank** [ramdor/Thetis#521]
<img width="307" alt="2024-10-13" src="https://github.com/user-attachments/assets/a4fcfd09-5072-484d-a81a-c6bbb75e91ca">
OS Windows 10 Pro updates as of this week, AMD 5900x, 64GB ram
error with Thetis at startup,
Removed 2.10.3.6 Beta 5 first.
Install 2.10.3.6 released today, error appears.
reinstall beta 5, rebuilds DB and then works

**Comment by ramdor** [comment]
This is not for the HermesLite. You will have to wait for @mi0bot to release the HL2 version at some point. There is a beta of the HL2 version here:

https://github.com/mi0bot/OpenHPSDR-Thetis/releases

Closing this..
