### ISSUE TITLE
[BUG] Incorrect USB Reporting

### ISSUE THREAD

**Issue by va7qi** [ramdor/Thetis#522]
**Describe the bug**
Incorrect Upper SB behavior
**To Reproduce**
Steps to reproduce the behaviour:
1. Set VFO A to 14.140 USB
2. Set VFA B to 3729 (well OK 3728.8) LSB
3. Swap VFO A <-> VFO B
4. 14,140, which should have been in USB mode is now in LSB mode.  The display shows USB in the old VFO frame, BUT the waterfall reveals that it is receiving in LSB.  Audio confirms the latter observation.

**Expected behaviour**
LSB should work on VFO b.

**Screenshots**
see attaced

**Desktop (please complete the following information):**
 - OS: Win 11 Home
![Uploading USBvsLSB.jpg…]()

**Additional context**

**Comment by ramdor** [comment]
You can only have a different mode on vfoB if using RX2, otherwise vffoB will match rx1 mode. If you are still having issues I would reset your filters by right clicking on them to get the popup. Closing this as can't replicate and no other reports.

**Comment by va7qi** [comment]
VFO B was on the second ADC.                     ....Erik.

On 2024-10-21 04:39:45, Richie ***@***.***> wrote:
You can only have a different mode on vfoB if using RX2, otherwise vffoB will match rx1 mode. If you are still having issues I would reset your filters by right clicking on them to get the popup. Closing this as can't replicate and no other reports.
