### ISSUE TITLE
[BUG]  Thetis v2.10.3.6 x64 final release WB problem

### ISSUE THREAD

**Issue by Beefus** [ramdor/Thetis#529]
**Describe the bug**
A clear and concise description of what the bug is. Include pertinent version numbers, such as Thetis vesion from title bar, firmware version, OS version etc.
Thetis v2.10.3.6 x64 (10/13/24) (FW v2.2.2 Protocol 2)
Radio Anan 7000DLE

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure Setup->BPF1/LPF->ByPass/55 Mhz BPF NOT checked (Rx front end filter engaged)
2. Click WB and note that ByPass/55 Mhz BPF IS checked (Rx front end filter NOT engaged)
3. WB box displays as expected
4. Click WB again (I did this because focus got changed to main Thetis screen and thought WB box not active)
5. Close WB box by clicking on X in upper right corner of WB box display
6. ByPass/55 Mhz BPF IS STILL checked (Rx front end filter NOT engaged) Causes overload of ADC1 due to 50KW MW broadcast station 5 miles away

**Expected behaviour**
Expected ByPass/55 Mhz BPF NOT checked when WB box closed

**Desktop (please complete the following information):**
 - WIndows 10
 - PC NUC 6i7KYK Skull Canyon with 2 NIC's, one dedicated to 7000DLE

**Additional context**
Wonderful work overall.  Thanks much! Jack, WB8BFS

**Comment by ramdor** [comment]
now fixed in 2.10.3.7 soon to be released, thanks
