### ISSUE TITLE
CW Auto Mode Switch Change

### ISSUE THREAD

**Issue by w3ub** [ramdor/Thetis#70]
I would like you to consider a change to the CW Auto Mode Switch operation. Right now, you could be in another mode, say LSB, and if you have this enabled and hit the paddles you do indeed switch to CW. But you remain there in CW mode.

I would like the operation to change such that after you send some CW you revert back to the mode you were in. Some of us, when operating phone, like to send some CW to the group we are talking with. But we want to return back to the mode we are in. I know that some other manufactures have this feature, such as Yaesu. 

I don't see the value in this option currently without such a change, but perhaps I am missing something.

/Doug

**Comment by ramdor** [comment]
return after some configurable delay?

**Comment by w3ub** [comment]
Yes, that would be good.
Doug

**Comment by ramdor** [comment]
implemented in #193 . Will be in the final release of 2.10.2
