### ISSUE TITLE
Panadapter frequency scale shifts when using XIT [BUG]

### ISSUE THREAD

**Issue by W2PA** [ramdor/Thetis#79]
**Describe the bug**
When XIT is active, going into transmit (MOX) causes the panadapter scale to shift by the XIT value.  This occurs on CW and SSB, and probably other modes I didn't test.  It occurs regardless of whether CTUN is on or off.  The transmitter is operating as it should but the display scale is wrong.

Thanks to Juha, NI2M, for noticing this.

**To Reproduce**
1. Tune to 28.010 in mode CWU, with DUP on, panafall view active, split off, MRx off, RIT off.  
2. Zoom in such that individual 1 kHz labels are visible, to easily see the effect
3. In main console, check both check boxes for "Show TX CW Freq" and "Show CW Zero Line
4. Turn on XIT and set its value to 1000 (1kHz)
5. Note the CW frequency line is on 28.010 and the CW Zero Line is on 28.011 (because of XIT), as they should be.
6. Hold key (or paddle) down in Semi mode
7. Transmitted signal appears on the display where it should, but the scale shifts, showing it at 28.012 instead of 28.011
8. Turn on QSK
9. Hit the key and confirm the actual transmitted signal is on 28.011 (this is also confirmed using a separate receiver)

To reproduce on USB, same procedure except:
1. 28.310 in USB
3. Skip this step
5. Skip
6. Click MOX or activate PTT
7. Note that the VFO line now appears on 28.312 instead of 28.311
8. Skip
9. Can confirm signal is actually on 28.311 using external receiver.

Related display scale behavior: If you turn on RIT alone (or with XIT - doesn't matter) with 1kHz setting, the wrong frequency (28.012 - should be 28.011) appears in receive mode, without transmitting.

**Expected behavior**
Transmitted signal should appear at 28.011 (or 28.311 for the USB example above).

**Screenshots**
None necessary

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, version 22H2, build 19045.2364

**Additional context**
ANAN-8000DLE, dedicated Ethernet connection, static IP addr, Thetis 2.9.0.7 x64 Protocol 2 v2.1.18 MM0LGE pre-release, compiled by me after cloning the current repo.

**Comment by ramdor** [comment]
yes rit and xit need re-working, they are a mess

**Comment by ramdor** [comment]
load of RIT fixes in the following branch : #136 

Will look at the XIT over next couple of days.

**Comment by ramdor** [comment]
after many attempts to resolve all these xit/rit issues, most are now solved. See vid below. Couple of things left to sort, but nearly there now.
https://youtu.be/82r9LPpGP2c

**Comment by ramdor** [comment]
hopefully latest merge into master will fix these issues. Please open new bug reports if issue found. #168
