### ISSUE TITLE
Allow VOX to override/bypass VAC for Phone

### ISSUE THREAD

**Issue by W4ATL** [ramdor/Thetis#87]
Request a new feature to allow VOX to monitor the MIC input when using VAC.

In contesting the operator will frequently use VOX to avoid repetitive keying of the footswitch for long periods of time. In order for a contesting program like N1MM+ to do voice keying of canned messages, VAC is enabled with the help of a third party program to route audio from N1MM+ to Thetis. The way VAC is configured now, the VOX circuitry is looking at audio from the Input source on the Thetis VAC setup window and not the MIC input. VOX cannot be used to talk to a station that answers your canned CQ from N1MM+ while VAC is enabled. You must use an external PTT switch and enable "Allow PTT to override/bypass VAC for Phone". This method will require constant use of the PTT footswitch when running stations using the N1MM+ voicekeyer.

If there were a checkbox to Allow VOX to override/bypass VAC for Phone, then the VOX circuitry would monitor the MIC input instead of the VAC Input line.

**Comment by oe3ide** [comment]
For contest I also use canned prerecorded audiofiles in N1MM, but you don't need VOX to get Thetis into TX. N1MM is setting Thetis correct to TX, plays the audio and returns to RX.
I made a test, I can use VOX (my regular phone audio is also via VAC1)... all is working great.
73 Ernst OE3IDE
