### ISSUE TITLE
TX inhibit input on Accessory connector no longer available in Thetis.

### ISSUE THREAD

**Issue by kc9xg** [ramdor/Thetis#95]
Radios without the Spreadout card (ANAN-10,100,200 models) no longer have Tx Inhibt checkbox settings available in Thetis.

![image](https://user-images.githubusercontent.com/18682554/221376760-2bbe23ec-e85e-4856-9815-55e6b84ba890.png)

Schematic accessory port J16-16/DB25-9 (Tx Inhibit) is connected to U25-5 digital input.
![image](https://user-images.githubusercontent.com/18682554/221377438-c872533e-237b-4431-a6d3-be0988962279.png)

Bill KC9XG

**Comment by ramdor** [comment]
re-added and cleaned functionaly. Some/all firmware does the inhibt, but UI is also now updated. Left in the reverse logic option for backwards compatibilty.
